// English UI copy is the key. Candidate data, JD text, notes and user input are never translated here.
export const uiZh: Record<string, string> = {
  "Working…": "正在处理…",
  "View activity": "查看工作进度",
  "Reconnecting…": "正在重新连接…",
  "Replying…": "正在回复…",
  "Thinking…": "思考中…",
  "Sent": "已发送",
  "Library": "资料库",
  "Forgotten preferences are not used in future replies.": "已忘记的偏好不会用于之后的回复。",
  "Preferences you forget appear here. You can restore or permanently delete them.": "忘记的偏好会显示在这里，可恢复或永久删除。",
  "Tell me in conversation: Remember that I prefer concise client updates.": "可以在对话中告诉我：“请记住，我希望客户进展更新简洁一些。”",
  "Try another search.": "试试其他关键词。",
  "No forgotten memories": "没有已忘记的记忆",
  "No saved preferences yet": "还没有保存工作偏好",
  "No matching memories": "没有匹配的记忆",
  "Could not delete memory": "无法删除记忆",
  "Memory deleted. Original conversations are unchanged.": "记忆已删除，原始对话保留。",
  "Delete permanently": "永久删除",
  "Deleting…": "正在删除…",
  "This permanently deletes the selected saved memories and their version history, including forgotten memories when clearing all. It cannot be undone. Original chats, CVs, JDs and scheduled reminders stay unchanged; past chats may still mention these preferences.": "将永久删除选中的记忆及其版本历史；清空时也会删除已忘记的记忆，无法恢复。原始对话、简历、职位和定时提醒不受影响，历史对话中仍可能包含这些偏好。",
  "Clear all memories?": "清空所有记忆？",
  "Delete memory permanently?": "永久删除这条记忆？",
  "Search memories": "搜索记忆",
  "Clear all memories": "清空所有记忆",
  "In use": "使用中",
  "Memory status": "记忆状态",
  "Only preferences you ask me to remember. Your CVs, JDs and reminders are managed separately.": "只保存你明确让我记住的偏好。简历、职位和定时提醒单独管理。",
  "Your personal preferences": "你的工作偏好",
  "Starting": "正在开始处理",
  "Preparing your draft": "正在准备草稿",
  "Tell your AI assistant which candidate and client role the recommendation is for. Review the prepared draft here or continue refining it in the conversation.": "告诉 AI 助理要为哪位候选人、哪个客户职位准备推荐稿。在这里审阅成稿，也可以回到对话继续修改。",
  "Clear document context": "清除文档上下文",
  "Revising": "正在修改",
  "No private notes": "不含私人笔记",
  "Candidate notes included": "包含候选人笔记",
  "Role records included": "包含职位记录",
  "candidate profiles": "位候选人公开履历",
  "Role requirements": "职位要求",
  "What would you like me to take care of?": "有什么事交给我？",
  "Your personal AI assistant for headhunting. Share the goal and the context; I’ll carry the work forward.": "你的专属猎头 AI 助理。交代目标，发来资料，我会接着往下办。",
  "Prepared work": "工作交付",
  "Candidate recommendation": "候选人推荐稿",
  "Preparing…": "正在准备…",
  "Saved draft · Nothing has been sent": "草稿已保存 · 尚未发送",
  "Ask for a revision": "继续修改",
  "Open document": "打开文档",
  "Opening your draft…": "正在打开草稿…",
  "Agreement paused": "约定已暂停",
  "Your agreed recurring update": "按约定准备的周期更新",
  "Please revise the draft: ": "请修改这份草稿：",
  "Work in progress": "正在为你处理",
  "Your next agreed updates": "接下来约定的更新",
  "Return to the conversation": "回到对话",

  "Your message": "你的消息",
  "Preferences": "偏好设置",
  "Manage your sign-in and personal preferences.": "管理登录方式与个人偏好。",
  "Choose the language for menus and controls.": "选择菜单和界面的显示语言。",

  "Save your current edits before continuing in a new conversation.": "保存当前修改后，再继续新对话。",
  "Save": "保存",
  "Your revised draft is saved.": "修订已应用，草稿已保存。",
  "Revision needs attention": "修订需要重试",
  "Saved document": "已保存的文档",
  "This saved document is ready to discuss or revise. Tell me what you want to change.": "已带上这份文档，可以直接讨论或交代修改。",
  "Pick up where you left off": "接着上次的工作",
  "Saved drafts to review": "待审核的草稿",
  "Reply needs attention": "回复需要重试",
  "In progress": "正在处理",
  "View original text": "查看原始文本",

  "What I remember": "我记住的事",
  "About our work": "我们的工作约定",
  "Your working preferences carry across conversations.": "你交代的工作习惯会延续到其他对话。",
  "Your working preferences and agreements, with their sources. Tell me in conversation when something changes.": "这里保留你的工作习惯、约定和来源。有变化时直接在对话里告诉我。",
  "No personal agreements saved yet. Tell me a habit or preference you want me to remember.": "还没有保存个人约定。你可以告诉我希望记住的习惯或偏好。",
  "Agreement name": "约定名称",
  "What to remember": "要记住的内容",
  "Original conversation": "原始对话",
  "Forget this": "忘记这件事",
  "Forgotten agreements": "已忘记的约定",
  "These stay out of future replies. You can restore them; original conversations and version history are kept.": "这些内容不再用于后续回复，你可以恢复。原始对话和版本历史仍保留。",
  "Restore": "恢复",
  "Forgotten": "已忘记",
  "Agreement updated": "约定已更新",
  "Remembered": "已记住",
  "Google could not verify this connection request. It may have expired or been replaced by another request. Click Connect Gmail to start again, and complete the Google screens within 5 minutes.": "Google 无法验证这次连接请求，可能已过期或被另一请求替换。请点击连接 Gmail 重新开始，并在 5 分钟内完成 Google 页面上的操作。",
  "Google did not complete the Gmail connection. Click Connect Gmail to try again and allow sending permission.": "Google 未完成 Gmail 连接。请点击连接 Gmail 重试并允许发送邮件权限。",
  "Deliver to client": "交付给客户",
  "Delivery method": "交付方式",
  "Share link": "分享链接",
  "Copy email": "复制邮件",
  "Send with Gmail": "通过 Gmail 发送",
  "Clients can open this link without signing in. It includes this recommendation and only the CVs listed below.": "客户无需登录即可打开链接，内容包括当前推荐说明和下方选中的简历。",
  "Link expires": "链接到期时间",
  "Copy link": "复制链接",
  "Open client link": "打开客户页面",
  "Revoke link": "撤销链接",
  "Your draft has changed. The existing link still shows the previously shared copy.": "草稿已有修改，现有链接仍显示之前发布的版本。",
  "Publish latest copy and replace old link": "发布最新版本并替换旧链接",
  "Creating link…": "正在创建链接…",
  "Create client link": "创建客户链接",
  "Copy the subject and body into your email app, then attach the selected CVs below.": "将主题和正文复制到邮箱，再添加下方选中的简历附件。",
  "Email subject": "邮件主题",
  "Email body": "邮件正文",
  "Connect your Google account to send this reviewed recommendation through Gmail. Hirelix requests sending permission, not inbox access.": "连接 Google 账户后，可通过 Gmail 发送审核好的推荐。Hirelix 只申请发送权限，不读取收件箱。",
  "Connect Gmail": "连接 Gmail",
  "Recipient email": "收件人邮箱",
  "The selected CVs below will be attached. This sends a real email to the recipient above.": "下方选中的简历将作为附件，点击发送后会向上述收件人发送真实邮件。",
  "Sent through Gmail": "已通过 Gmail 发送",
  "Sending through Gmail…": "正在通过 Gmail 发送…",
  "Gmail did not confirm delivery. Check Sent in Gmail before trying again.": "Gmail 未确认发送结果，请先到 Gmail 的已发送文件夹核实，避免重复发送。",
  "Send email": "发送邮件",
  "Disconnect Gmail": "断开 Gmail",
  "Sending failed": "发送失败",
  "Delivery unconfirmed": "发送结果待核实",
  "Selected CV attachments": "选中的简历附件",
  "No CV attachments selected. Only the recommendation text will be shared.": "未选择简历附件，本次仅交付推荐正文。",
  "Could not create share link": "无法创建分享链接",
  "Could not revoke link": "无法撤销链接",
  "Could not connect Gmail": "无法连接 Gmail",
  "Could not disconnect Gmail": "无法断开 Gmail",
  "Connect Gmail before sending": "发送前请连接 Gmail",
  "Reconnect Gmail to renew sending permission": "请重新连接 Gmail，更新发送授权",
  "Gmail declined sending. Reconnect Gmail and check that the Gmail API is enabled.": "Gmail 拒绝发送。请重新连接 Gmail，并检查 Gmail API 是否启用。",
  "Gmail rejected this email. Check the recipient and attachments before trying again.": "Gmail 拒绝了此邮件，请核对收件人和附件后重试。",
  "Only client candidate recommendations can be shared": "只有面向客户的候选人推荐可以分享",
  "The selected CVs are too large for one email. Use a share link instead.": "选中的简历超过单封邮件大小限制，请使用分享链接。",

  "Help me organize these candidate files into my workspace.": "帮我把这些候选人资料整理并保存到资料库。",
  "Give files to AI assistant": "交给 AI 助理整理",
  "Keep this page open until your files and message are sent.": "文件和消息发送完成前，请保持此页面打开。",
  "Retry": "重试",
  "Ready to send": "待发送",
  "Upload failed. Check your connection and retry.": "上传失败，请检查网络后重试。",
  "External sourcing has been retired. Your previous results are kept here.": "外部人才寻访已停止提供，历史结果保留在这里。",
  "Could not load previous results": "暂时无法加载历史结果",
  "Add files": "添加资料",
  "Drop files here": "把资料放在这里",
  "Share the material. Tell me what you want done.": "把资料交给我，告诉我你想完成什么。",
  "Tell me what you want to get done. Drop in CVs, JDs and notes together.": "告诉我你想完成什么，简历、JD 和笔记可以一起丢进来。",
  "Add up to 20 files per message.": "每条消息最多添加 20 个文件。",
  "Use CSV, PDF, DOCX, TXT or Markdown files.": "支持 CSV、PDF、DOCX、TXT 和 Markdown 文件。",
  "Each file must be non-empty and up to 4 MB.": "每个文件须非空，且不超过 4 MB。",
  "Some files need attention. Retry or remove them, then send. Uploaded files are kept.": "部分文件需要处理，请重试或移除后发送。已上传的文件会保留。",

  "PERSONAL AGENT": "私人 AI 助理",
  "per year": "每年",
  "Personal Agent": "私人 AI 助理",
  "Trial ended": "试用已结束",
  "7-day free trial": "7 天免费试用",
  "{count} AI credits remaining": "剩余 {count} AI 额度",
  "Starts with your first task · No card": "首次工作时开始 · 无需银行卡",
  "View plan and subscription →": "查看套餐和订阅 →",
  "Subscription and AI usage": "订阅和 AI 用量",
  "Your subscription is active. Your agent is ready.": "订阅已生效，私人 AI 助理已准备就绪。",
  "Waiting for payment confirmation from Paddle. Your access will update here after confirmation. If this takes longer than a minute, refresh or contact support.": "正在等待 Paddle 确认付款。确认后，此处将更新你的使用权限。如超过一分钟，请刷新页面或联系支持。",
  "Personal Agent subscription": "私人 AI 助理订阅",
  "Your trial has ended": "你的试用已结束",
  "7-day Personal Agent trial": "私人 AI 助理 7 天试用",
  "{remaining} of {limit} AI credits remaining.": "剩余 {remaining} / {limit} AI 额度。",
  "Current allowance ends {date}.": "当前额度有效期至 {date}。",
  "Your trial starts with your first AI task. No card required.": "试用从首次 AI 工作开始，无需银行卡。",
  "Used {used} AI credits. {reserved} reserved for work in progress.": "已用 {used} AI 额度，处理中预留 {reserved}。",
  "Not enough AI credits for this work. Your saved work is still available. Open Settings → Billing to check your allowance.": "AI 额度不足以完成这项工作。已保存的工作仍可查看。请打开 设置 → 计费 查看额度。",
  "AI work uses credits based on the services consumed. Longer or more complex work may use more credits. Credits are reserved while work is running; only completed work is charged. System retries, automatic indexing and follow-on imports are included. Paid credits reset on the first of each month (UTC); unused credits do not roll over.": "按实际服务消耗扣除 AI 额度，较长或复杂的工作可能消耗更多额度。处理期间暂时预留额度，完成后结算；失败工作不扣额度。系统重试、自动索引和后续导入包含在内。付费额度在每月 1 日（UTC）重置，未用完的额度不结转。",
  "Renews automatically until canceled.": "取消前将自动续订。",
  "View subscription": "查看订阅",
  "Update payment method": "更新付款方式",
  "Cancel subscription": "取消订阅",
  "Contact support to manage or cancel your subscription": "联系支持管理或取消订阅",
  "Back to your agent": "返回私人 AI 助理",
  "$49 / month": "$49 / 月",
  "$490 / year · save $98": "$490 / 年 · 节省 $98",
  "Includes {count} AI credits each calendar month. One personal workspace. Candidate records, ongoing roles, client drafts, and document exports.": "每个自然月包含 {count} AI 额度。一个私人工作台，可管理候选人记录、进行中的职位、客户草稿并导出文档。",
  "Subscribe for $49 / month": "以 $49 / 月订阅",
  "Subscribe for $490 / year": "以 $490 / 年订阅",
  "USD, plus applicable tax shown at checkout. Payment is collected now when you subscribe.": "以美元计价，另加结账时显示的适用税费。订阅时立即收款。",
  "Renews monthly until canceled.": "取消前按月续订。",
  "Renews annually until canceled.": "取消前按年续订。",
  "Your saved work remains available when AI access ends.": "AI 使用权限结束后，仍可查看已保存的工作。",
  "Refund policy": "退款政策",
  "Could not open subscription settings.": "无法打开订阅设置。",
  "Could not open billing.": "无法打开计费页面。",
  "Scheduled search updates": "定期进展草稿",
  "Set an agreement": "设置更新约定",
  "Edit agreement": "编辑更新约定",
  "Prepare a draft for your review. Nothing is sent to a client. Each completed draft uses AI credits.": "按约定准备待审阅草稿，不会发送给客户。每份完成的草稿消耗 AI 额度。",
  "Next draft": "下次准备",
  "Pause agreement": "暂停约定",
  "Resume agreement": "恢复约定",
  "Draft prepared for review": "草稿已准备，待您审阅",
  "Draft needs attention": "草稿需要处理",
  "Open draft": "打开草稿",
  "Search update agreement": "进展草稿约定",
  "Frequency": "频率",
  "Every week": "每周",
  "Every two weeks": "每两周",
  "Weekday": "星期",
  "Sunday": "星期日",
  "Monday": "星期一",
  "Tuesday": "星期二",
  "Wednesday": "星期三",
  "Thursday": "星期四",
  "Friday": "星期五",
  "Saturday": "星期六",
  "Local time": "当地时间",
  "Timezone": "时区",
  "Uses local clock time. During daylight-saving gaps the time moves forward; repeated times use standard time. The saved agreement shows the next actual draft time.": "按当地时间运行。夏令时跳过的时间顺延，重复时间采用标准时间。保存后显示下次实际运行时间。",
  "Report the period since the previous scheduled draft, or the preceding one or two weeks for the first draft. Delayed runs catch up once. A failed draft can be retried without losing its original evidence.": "汇报自上次定期草稿以来的记录；首次覆盖此前一周或两周。延误时合并补做一次，失败可保留原依据重试。",
  "Candidate profiles to include": "纳入草稿的候选人资料",
  "Include dated role records, including future client feedback, in drafts": "纳入带日期的职位记录，包括此后保存的客户反馈",
  "Include dated private notes for the selected candidates, including future notes, in drafts": "纳入所选候选人带日期的私人备注，包括此后保存的备注",
  "Unselected private notes, contact details and original files are excluded. Review every draft before sharing.": "未选择的私人备注、联系方式和原始文件不会纳入。分享前请审阅每份草稿。",
  "Notify me only when the selected evidence changes": "只在所选依据变化时提醒我",
  "Agreement enabled": "启用更新约定",
  "Save agreement": "保存约定",
  "Drafts ready": "草稿已准备",
  "Mark as read": "标记已读",
  "Support and privacy requests": "支持与隐私请求",
  "Contact support for account-wide export or deletion. Requests are reviewed after ownership verification; this does not delete your account automatically.": "如需导出整个账户的数据或删除账户，请联系支持。确认账户归属后人工处理；此入口不会自动删除账户。",
  "Discard your edits to this proposal?": "放弃对这项提案的修改吗？",
  "Priorities": "重点要求",
  "note": "备注",
  "call": "通话",
  "email": "邮件",
  "feedback": "反馈",
  "Review sharing permission": "核对资料分享授权",
  "Review the evidence and sharing permission before saving": "保存前核对授权依据和状态",
  "Saving creates a source record and updates sharing permission for this role. It does not send a recommendation.": "保存后会同时留下依据记录并更新这个职位的资料分享授权；不会发送推荐。",
  "Sharing permission": "资料分享授权",
  "Save permission and record": "保存授权与依据",
  "Open saved item": "打开",
  "Attach a file": "添加文件",
  "· Attached file": "· 对话附件",
  "Drop a file to ask your AI assistant": "拖入文件，交给 AI 助理处理",
  "Let's move the work forward.": "我们接着推进工作。",
  "% overall": "总体 %",
  "+ years": "+ 年",
  ". I’ll ask which details to keep.": "。我会询问要保留哪些细节。",
  ". You can return to this draft later.": "。你可以稍后回到此草稿。",
  "/ month": "/月",
  "01 · Candidates": "01 · 候选人",
  "02 · Judgment": "02 · 判断",
  "03 · Deliverable": "03 · 交付物",
  "1 free client role · No credit card": "1 个免费客户职位 · 无需信用卡",
  "6-digit code": "6 位验证码",
  "A brief you can defend": "一份站得住脚的简报",
  "A clear introduction for every candidate.": "为每位候选人提供清晰的介绍。",
  "A complete picture, over time.": "完整的候选人档案，随工作持续积累。",
  "A JD is one useful starting point. Your agent can also work from people you already know.": "JD 是一个有用的起点。你的 AI 助理也可以从你已认识的人入手。",
  "A possible match exists. Add a separate candidate only if this is a different person.": "存在可能匹配。仅当这是不同的人时，才添加单独的候选人。",
  "Your private AI assistant for the candidates and roles you know.": "为你熟悉的候选人和职位服务的私人 AI 助理。",
  "A selected CV is not available for these candidates": "这些候选人没有可用的已选简历",
  "A selected note belongs to an unselected candidate": "已选中的备注属于未选中的候选人",
  "A selected note belongs to another client role": "所选备注属于其他客户职位",
  "A selected record is not part of this role": "所选记录不属于此职位",
  "A sentence or two about your background — used to make outreach feel personal and credible.": "用一两句话介绍您的背景——用于让外联显得亲切可信。",
  "A short title is enough; a JD snippet is better.": "简短标题即可；附上 JD 片段更好。",
  "A source's association cannot be changed while editing its text": "编辑来源文本时无法更改其关联",
  "A thinking partner with your own long-term context.": "一位掌握你长期背景的思考伙伴。",
  "A.": "A.",
  "Access": "访问权限",
  "Account": "账户",
  "active": "进行中",
  "Active searches": "进行中的寻访",
  "Active Shortlists": "活跃短名单",
  "Add a candidate": "添加候选人",
  "Add a candidate to this role": "为该职位添加候选人",
  "Add a header row and at least one candidate to this CSV": "为此 CSV 添加表头行和至少一名候选人",
  "Add a password so you can sign in without waiting for an email code.": "添加密码，这样无需等待邮件验证码即可登录。",
  "Add a person or import your existing records. Their notes and relationships stay with them across roles.": "添加人员或导入现有记录。他们的备注和关系会随其在各职位间保留。",
  "Add a record": "添加记录",
  "Add a record for this candidate and role": "为此候选人和职位添加记录",
  "Add a role": "添加职位",
  "Add as a new candidate": "添加为新候选人",
  "Add candidate": "添加候选人",
  "Add from candidates": "从候选人中添加",
  "Add from your pool": "从人才库中添加",
  "Add record": "添加记录",
  "Add role": "添加职位",
  "Add sourcing capacity when you need it.": "需要时增加人才寻访能力。",
  "Add the record supporting this sharing decision": "添加支持该分享决定的记录",
  "Add this candidate to the role before preparing a submission": "准备候选人推荐前，将该候选人加入职位",
  "Add your first client role from its JD.": "通过 JD 添加您的第一个客户职位。",
  "Add your first role": "添加您的第一个职位",
  "Added": "已添加",
  "Advancement risks": "晋升风险",
  "ago": "前",
  "All roles": "所有职位",
  "Already have an account?": "已有账户？",
  "Already in your pool?": "已在人才库中？",
  "Apply requirements": "应用要求",
  "Apply revision": "应用修订",
  "Ask about": "询问关于",
  "Ask about a JD, a person, or your candidate pool…": "询问 JD、某个人或你的候选人池……",
  "Ask about this role": "询问此职位",
  "Ask for role-specific judgment": "询问与职位相关的判断",
  "Ask why someone may fit this role and what evidence is missing.": "询问某人为何可能适合此职位，以及缺少哪些证据。",
  "Ask your agent": "询问你的 AI 助理",
  "Ask, paste a JD, or share a conversation note…": "提问、粘贴 JD，或分享对话备注…",
  "Assessment basis": "评估依据",
  "AI assistant conversation": "AI 助理对话",
  "At least 8 characters": "至少 8 个字符",
  "Attach a CSV or CV": "附上 CSV 或简历",
  "Attach a CSV, text PDF or DOCX candidate file.": "上传 CSV、文本型 PDF 或 DOCX 候选人文件。",
  "Attach candidate file": "附上候选人文件",
  "Attach candidates": "关联候选人",
  "Auto-refreshes every 5 seconds while this page is visible.": "此页面可见时每 5 秒自动刷新。",
  "Back to candidate pools": "返回候选人池",
  "Back to candidates": "返回候选人",
  "Back to dashboard": "返回仪表盘",
  "Back to role": "返回职位",
  "Best opening angle": "最佳开场角度",
  "Best single ranking signal for who to review first.": "决定先审核谁的最佳单一排名信号。",
  "Best usable proof": "最佳可用佐证",
  "Beta access": "Beta 访问权限",
  "Beta code": "Beta 邀请码",
  "Billing": "计费",
  "Billing and usage": "计费与用量",
  "Billing portal is not configured yet. Email": "计费门户尚未配置。请发送邮件至",
  "Billing unavailable": "计费不可用",
  "Blocking constraints": "硬性限制",
  "Body copied": "正文已复制",
  "Book 10 min feedback": "预约 10 分钟反馈",
  "Brief parsing usually finishes in under 1 minute": "职位要求解析通常在 1 分钟内完成",
  "Brief pending": "简报待生成",
  "Brief ready": "简报已就绪",
  "Brief ready in": "简报即将就绪",
  "Bring a client’s JD, a conversation with a candidate, or a recommendation you need to prepare. I’ll help you work with what you have.": "带上客户 JD、与候选人的沟通记录，或你需要准备的候选人推荐。我会帮你利用现有材料。",
  "Bring a real client JD": "带来一份真实的客户 JD",
  "Bring in the people worth considering.": "引入值得考虑的人选。",
  "Bring your client roles and your own candidate knowledge to one private agent. Ask better questions and prepare stronger recommendations.": "将您的客户职位和您自己的候选人知识汇集到一个私人 AI 助理中。提出更好的问题，准备更有力的推荐。",
  "Bring your existing candidates.": "导入你现有的候选人。",
  "Build brief": "生成简报",
  "Build shortlist": "生成短名单",
  "Building candidate pool...": "正在构建候选人池...",
  "Built for professional headhunters": "为专业猎头打造",
  "Built for technical headhunters.": "为技术猎头打造。",
  "Built for technical recruiters and headhunters. If your candidate pool misses the mark or your billing looks wrong, email": "专为技术招聘人员和猎头打造。如果你的候选人池不理想或计费有误，请发送邮件至",
  "By meaning": "按语义",
  "Call note": "通话备注",
  "Can I still run a new search?": "我还能发起新的寻访吗？",
  "Can it distinguish my notes from profile claims?": "它能区分我的备注与资料中的说法吗？",
  "Cancel": "取消",
  "Cancel anytime from billing settings or by emailing support@hirelix.online.": "可随时从账单设置中取消，或发送邮件至 support@hirelix.online 取消。",
  "Cancellation timing": "取消时间",
  "Candidate": "候选人",
  "Candidate details": "候选人详情",
  "Candidate file": "候选人文件",
  "Candidate import": "候选人导入",
  "Candidate import in conversation": "在对话中导入候选人",
  "Candidate indexing": "候选人资料索引",
  "Candidate is not linked to this role": "候选人未关联到此职位",
  "Candidate list": "候选人列表",
  "Candidate pool complete": "候选人池已完成",
  "Candidate pool not found": "未找到候选人池",
  "Candidate pool ready": "候选人池已就绪",
  "Candidate profile": "候选人档案",
  "Candidate queue": "候选人队列",
  "Candidate research": "候选人调研",
  "Candidate research available": "可进行候选人调研",
  "Candidate research can strengthen technical fit and outreach confidence when you choose to run it.": "当你选择运行时，候选人调研可增强技术匹配度与外联信心。",
  "Candidate research has not been run for this candidate yet.": "尚未对该候选人进行调研。",
  "Candidate research has not been run yet. Current ranking stays based on profile fit and risk signals.": "尚未进行候选人调研。当前排名仍基于资料匹配度与风险信号。",
  "Candidate research has not been run yet. Use the profile fit notes, or research this candidate before citing outside sources.": "尚未进行候选人调研。请参考资料匹配度备注，或在引用外部来源前先调研该候选人。",
  "Candidate research is pending. Current ranking stays based on profile fit and risk signals until the background check finishes.": "候选人调研待处理。在背景调查完成前，当前排名仍基于资料匹配度与风险信号。",
  "Candidate review is underway. The pool will appear after the first pass finishes.": "候选人审核正在进行中。首轮处理完成后将显示候选人池。",
  "Candidate sections": "候选人板块",
  "Candidate Selling Kit": "候选人推介工具包",
  "Candidate status": "候选人状态",
  "Candidate submission": "候选人推荐",
  "Candidate submissions": "候选人推荐",
  "candidate": "候选人",
  "candidates": "候选人",
  "Candidates": "候选人",
  "Candidates to include as context": "纳入上下文的候选人",
  "Candidates to recommend": "推荐候选人",
  "candidates ·": "候选人 ·",
  "Change password": "修改密码",
  "Check": "检查",
  "Check the extracted profile": "检查提取的资料",
  "Check the suggested mapping. For names, you can combine first and last name columns.": "检查建议的映射。对于姓名，可以合并名字和姓氏列。",
  "Check wording, facts and permission before you share. Copying this draft does not mark it submitted.": "分享前请检查措辞、事实和权限。复制此草稿不会将其标记为已提交。",
  "Choose a candidate": "选择候选人",
  "Choose a candidate or role for this record": "为此记录选择候选人或职位",
  "Choose a client role and one or more candidates. Prepare a draft from the information you decide to share, then review and edit it before sending it yourself.": "选择客户职位和一个或多个候选人。根据你决定分享的信息准备草稿，然后在自行发送前审阅并编辑。",
  "Choose a client-role tier. Annual gives you the lower monthly rate.": "选择客户职位档位。年付可享更低的月费率。",
  "Choose a file up to 4 MB.": "选择不超过 4 MB 的文件。",
  "Choose a record": "选择记录",
  "Choose a role": "选择职位",
  "Choose a valid reporting period": "选择有效的汇报周期",
  "Choose a value for each difference. Previous versions and the original imported file will remain available.": "为每处差异选择一个值。先前版本和原始导入文件仍将保留。",
  "Choose an existing candidate and review the fields before merging": "选择现有候选人并在合并前查看字段",
  "Choose at least one candidate for this submission": "为本次候选人推荐选择至少一名候选人",
  "Choose each candidate, record and CV once": "为每位候选人、每条记录和每份简历各选择一次",
  "Choose existing CSV columns": "选择现有的 CSV 列",
  "Choose one CV version per candidate": "为每位候选人选择一份简历版本",
  "Choose the column or columns containing the candidate name": "选择包含候选人姓名的一列或多列",
  "Choose the exact CV version for each person. No file is attached automatically. You can save a draft while a CV is missing.": "为每个人选择确切的简历版本。不会自动附加文件。缺少简历时也可保存草稿。",
  "Choose the language used throughout your workspace. Candidate records and your own notes keep their original wording.": "选择整个工作区使用的语言。候选人记录和您自己的备注保留原文。",
  "Choose the people and source material to include": "选择要纳入的人员和来源材料",
  "Choose the people and supporting material you want to share.": "选择你想分享的人员和辅助材料",
  "Choose the people you want to introduce. Drafting and exporting are kept separate from recording an actual submission.": "选择你想介绍的人员。起草和导出与记录实际候选人推荐相互独立。",
  "Choose the role whose requirements changed.": "选择要求发生变化的职位。",
  "Choose two different candidates": "选择两名不同的候选人",
  "Choose your interface language": "选择界面语言",
  "Client": "客户",
  "Client & practical details": "客户及实务详情",
  "Client brief": "客户简报",
  "Client brief and outreach workflow": "客户简报与外联流程",
  "Client brief preview": "客户简报预览",
  "Client briefs remain drafts until you review them": "客户简报在您审核前保持草稿状态",
  "Client contact and practical details": "客户联系人与实务详情",
  "Client drafts use this language by default. You can choose a different language when preparing each draft.": "客户材料草稿默认使用此语言；准备每份草稿时都可以单独选择。",
  "Client material": "客户材料",
  "Client not recorded": "未记录客户",
  "Client not yet recorded": "尚未记录客户",
  "Client preview": "客户预览",
  "Internal review": "内部审核",
  "Document preview": "材料预览",
  "Title copied": "已复制标题",
  "Copy title": "复制标题",
  "For internal review. Use the assistant to prepare client material before recording a client submission. Unknown facts and sharing permission still need confirmation.": "此材料用于内部审核。请先让 AI 助理转换为客户材料，再记录向客户提交；未知事实和分享授权仍需确认。",
  "Client role": "客户职位",
  "Client roles": "客户职位",
  "client roles left this cycle": "本周期剩余客户职位",
  "Client-ready ranked pool": "可供客户查看的排序候选人池",
  "Close": "关闭",
  "Close navigation": "关闭导航",
  "Close role": "关闭职位",
  "Close sign in dialog": "关闭登录对话框",
  "Close sign in dialog backdrop": "关闭登录对话框背景遮罩",
  "closed": "已关闭",
  "Closed. Your records and candidate relationships remain available.": "已关闭。你的记录和候选人关系仍然可用。",
  "Collapse": "折叠",
  "Completed searches": "已完成寻访",
  "Confirm column mapping": "确认列映射",
  "Confirm current interest, compensation range, and role scope before submitting.": "提交前请确认当前意向、薪酬范围和职位范围。",
  "Confirm mapping": "确认映射",
  "Confirm password": "确认密码",
  "Confirm sourcing brief": "确认人才寻访简报",
  "Confirm the import preview first": "请先确认导入预览",
  "Confirmed": "已确认",
  "confirmed": "已确认",
  "Constraint fit": "约束匹配",
  "Constraint risk": "约束风险",
  "Contact": "联系",
  "Contact ready": "可联系",
  "Contact unlock": "解锁联系方式",
  "Contact YieldMirror about Hirelix.": "联系 YieldMirror 了解 Hirelix。",
  "Contact | Hirelix": "联系我们 | Hirelix",
  "contacted": "已联系",
  "Continue with email": "使用邮箱继续",
  "Continue with Google": "使用 Google 继续",
  "Continue in a new conversation": "在新对话中继续",
  "Continue with this role.": "使用此职位继续",
  "Continue with your AI assistant": "继续使用你的 AI 助理",
  "Control how you appear in outreach drafts. Candidates see your name and firm, not your client's confidential details.": "控制在触达草稿中的展示方式。候选人看到的是你的姓名和公司，而非客户的机密信息。",
  "Conversation role": "对话角色",
  "Copied": "已复制",
  "Copy": "复制",
  "Copy a client brief before you start outreach.": "开始外联前复制客户简报。",
  "Copy all": "复制全部",
  "Copy All": "全部复制",
  "Copy body": "复制正文",
  "Copy brief": "复制简报",
  "Copy client brief": "复制客户简报",
  "Copy opener": "复制开场白",
  "Copy subject": "复制主题",
  "Copy text": "复制文本",
  "Copy-ready opener": "可直接复制的开场白",
  "Could not access the clipboard. Select and copy the text.": "无法访问剪贴板。请选择并复制文本。",
  "Could not load this candidate pool. Please try again.": "无法加载此候选人库。请重试。",
  "Could not record this here. Please use Reply by email instead.": "无法在此记录。请改用邮件回复。",
  "Could not save language preference": "无法保存语言偏好",
  "Could not send the code.": "无法发送验证码。",
  "Could not start candidate research.": "无法启动候选人调研。",
  "Create a private, no-login client link": "创建无需登录的私密客户链接",
  "Creating link": "正在创建链接",
  "CSV": "CSV",
  "CSV, text PDF or DOCX · Up to 4 MB per file": "CSV、文本 PDF 或 DOCX · 每个文件最大 4 MB",
  "Current annual": "当前年薪",
  "Current basis": "当前依据",
  "Current basis:": "当前基准：",
  "Current monthly": "当前月薪",
  "Current password": "当前密码",
  "Current plan": "当前方案",
  "Current role / headline": "当前职位 / 职业标题",
  "Current role not recorded": "未记录当前职位",
  "Current work": "当前工作",
  "CV attachments": "简历附件",
  "CV attachments belong to candidate submissions": "简历附件属于候选人推荐",
  "CV attachments by candidate": "按候选人分组的简历附件",
  "Data retention and security": "数据保留与安全",
  "Date not recorded": "未记录日期",
  "Decision": "决策",
  "Declined": "已拒绝",
  "declined": "已拒绝",
  "Delete candidate": "删除候选人",
  "Delete sourcing task": "删除人才寻访任务",
  "Delivery recorded": "已记录交付",
  "Describe the experience or past conversation you remember": "描述你记得的经历或过往对话",
  "Describe this role’s actual progress over a defined period.": "描述该职位在指定期间内的实际进展。",
  "Deselect all": "取消全选",
  "Details": "详情",
  "Direct match to the JD, domain, title family, and required stack.": "与JD、领域、职位族及所需技术栈直接匹配。",
  "Direction for this draft": "此草稿的方向",
  "Disclaimer and limitation of liability": "免责声明与责任限制",
  "Do not import this field": "不导入此字段",
  "Document content": "文档内容",
  "Document history": "文档历史",
  "Document title": "文档标题",
  "Does it send the weekly brief?": "它会自动发送定期进展说明吗？",
  "done": "已完成",
  "Download original": "下载原件",
  "Download source file": "下载源文件",
  "Draft": "草稿",
  "draft": "草稿",
  "Draft a submission": "起草候选人推荐",
  "Draft language": "草稿语言",
  "Draft the client update": "起草给客户的进展说明",
  "Drafts to finish": "待完成的草稿",
  "e.g. Apex Search Partners (optional)": "例如：Apex Search Partners（可选）",
  "e.g. Sarah Chen": "例如：Sarah Chen",
  "e.g. Senior engineering roles at Series A–C startups": "例如：A–C轮初创公司的资深工程职位",
  "Each CSV column needs a unique, non-empty header": "每个 CSV 列都需要一个唯一且非空的表头",
  "Edit": "编辑",
  "Edit candidate": "编辑候选人",
  "Edit draft": "编辑草稿",
  "Edit record": "编辑记录",
  "Edit role": "编辑职位",
  "Edit the constraints that would change who you contact first.": "编辑会改变你优先联系谁的条件。",
  "Editable brief": "可编辑简报",
  "Education": "教育背景",
  "Email": "邮箱",
  "Email code": "邮箱验证码",
  "Email or password is not correct.": "邮箱或密码不正确。",
  "Email record": "邮件记录",
  "Ends": "结束",
  "Engineering depth from the profile, strengthened by candidate research when you run it.": "来自资料的工程深度，在您开展候选人调研时得到增强。",
  "English": "英文",
  "Enter a valid work email first.": "请先输入有效的工作邮箱。",
  "Enter your current password first.": "请先输入当前密码。",
  "Enter your email and password.": "请输入邮箱和密码。",
  "Enter your email and the code from your inbox.": "请输入邮箱和收件箱中的验证码。",
  "error": "失败",
  "every candidate conversation.": "每次候选人沟通。",
  "Evidence": "证据",
  "Evidence pending": "证据待补充",
  "Evidence score": "证据评分",
  "Evidence status": "证据状态",
  "Evidence-based ranking": "基于证据的排名",
  "Example: need staff-level Kafka/Flink platform owners, not ETL-heavy profiles": "例如：需要 Staff 级 Kafka/Flink 平台负责人，而不是偏重 ETL 的候选人",
  "Existing candidate": "现有候选人",
  "Existing search, when needed": "需要时使用人才寻访",
  "Expand": "展开",
  "Expand pool": "扩展人才池",
  "Expanding": "正在扩展",
  "Expanding pool": "正在扩展人才池",
  "Expansion reason": "扩展原因",
  "Experience": "工作经历",
  "Expertise": "专长",
  "Export": "导出",
  "Export CSV": "导出 CSV",
  "Export profile & records": "导出个人资料与记录",
  "Export this pool": "导出此人才池",
  "Features": "功能",
  "Filter by expertise": "按专长筛选",
  "Filter by location": "按地点筛选",
  "Filter by role or JD...": "按职位或 JD 筛选...",
  "Find a candidate": "查找候选人",
  "Find a submission": "查找候选人推荐",
  "Find candidates": "查找候选人",
  "Finding candidates in your private pool": "在您的私人人才库中查找候选人",
  "Finding profiles": "正在寻找候选人",
  "Finding profiles for this role.": "正在为该职位查找候选人资料。",
  "Finding relevant passages in this candidate's source records": "在此候选人的来源记录中查找相关段落",
  "Finish or retry the previous reply before sending another message": "请先完成或重试上一条回复，再发送另一条消息",
  "Firm / agency name": "公司/机构名称",
  "First client role": "首个客户职位",
  "Fit evidence": "匹配证据",
  "Fit reviewed": "匹配度已审核",
  "Focus area": "专注领域",
  "For a few active client roles.": "适用于少量活跃客户职位。",
  "For a larger client-role desk.": "适用于更大规模的客户职位业务。",
  "For a technical headhunter covering a few active client roles.": "适合同时处理少量客户职位的技术猎头。",
  "for plan changes or invoices.": "用于套餐变更或发票。",
  "For recruiters running a larger active client-role desk.": "适合同时处理较多客户职位的猎头。",
  "For technical headhunters covering a few active client roles.": "适合负责少量活跃客户职位的技术猎头。",
  "For technical recruiters": "适合技术招聘人员",
  "Free plan": "免费套餐",
  "From": "开始时间",
  "Sender email": "发件人邮箱",
  "Gmail data use and privacy": "Gmail 数据使用与隐私说明",
  "Full client-ready brief export is included on Pro.": "Pro 版包含完整的可直接交付客户的简报导出。",
  "Full name": "姓名",
  "Full pool": "完整人才池",
  "Full pool (": "完整人才池 (",
  "Gaps and uncertainties": "差距与不确定性",
  "Generate a grounded LinkedIn InMail from the candidate profile and current research evidence.": "根据候选人资料和当前调研证据生成有依据的 LinkedIn InMail。",
  "Generate LinkedIn draft": "生成 LinkedIn 草稿",
  "Generate outreach": "生成外联内容",
  "Go back": "返回",
  "Google sign-in failed to start.": "Google 登录启动失败。",
  "Happened": "已发生",
  "Hard blocker": "硬性阻碍",
  "Hard filters": "硬性筛选条件",
  "Hide": "隐藏",
  "Hide column details": "隐藏列详情",
  "Hide JD": "隐藏 JD",
  "hirelix": "hirelix",
  "Hirelix": "Hirelix",
  "Hirelix did not find enough sourced profiles to build a ranked pool yet.": "Hirelix 尚未找到足够的人才寻访档案来生成排名候选人池。",
  "Hirelix home": "Hirelix 首页",
  "Hirelix interpreted this role as:": "Hirelix 将此职位解读为：",
  "Hirelix is built for technical headhunters. For billing issues, missing credits, or candidate pool problems, email": "Hirelix 专为技术猎头打造。如有账单问题、额度缺失或候选人池问题，请发送邮件至",
  "Hirelix is operated by YieldMirror.": "Hirelix 由 YieldMirror 运营。",
  "Hirelix is still building the sourcing brief from the JD. This section will fill in as soon as parsing finishes.": "Hirelix 仍在根据 JD 构建人才寻访概要。解析完成后，此部分将自动填充。",
  "Hirelix is still refining the remaining scores in the background.": "Hirelix 仍在后台完善剩余评分。",
  "Hirelix reads the JD, shows the sourcing brief, then builds a ranked candidate pool with a recommended shortlist inside it.": "Hirelix 读取 JD，展示人才寻访概要，然后构建一个排名候选人池，并在其中给出推荐入围名单。",
  "Hirelix scored the profile fit and risks. Candidate research can be added on demand.": "Hirelix 已评估候选人匹配度与风险。可按需补充候选人调研。",
  "Hirelix stopped further automatic sourcing because the current thesis did not produce actionable candidates.": "由于当前寻访思路未产出可推进的候选人，Hirelix 已停止后续自动人才寻访。",
  "Hirelix understands the role and is moving into recall.": "Hirelix 已理解职位，正在进入召回阶段。",
  "HIRELIX-BETA-XXXX-XXXX": "HIRELIX-BETA-XXXX-XXXX",
  "History": "历史记录",
  "hold": "保留",
  "Home": "首页",
  "How it works": "运作方式",
  "How realistic this person is to contact now, given mobility and logistics signals.": "结合流动性与后勤信号，判断现在联系此人的可行程度。",
  "How should this record be saved?": "这条记录应如何保存？",
  "How to widen this pool": "如何扩大此候选人池",
  "How we use information": "我们如何使用信息",
  "How you present yourself to candidates. Your client's name stays confidential.": "你如何向候选人展示自己。客户名称将保密。",
  "Hybrid": "混合",
  "I can compare the role with people you saved, show which facts support each potential fit, and point out what still needs verification. I will keep your notes distinct from profile claims.": "我可以将职位与你保存的人选进行比较，展示哪些事实支持每个潜在匹配，并指出仍需核实的内容。我会将你的备注与资料中的说法区分开。",
  "I have your file. I’ll read the candidates and check for duplicates.": "我已收到你的文件。我会读取候选人并检查重复项。",
  "Identity": "身份",
  "Identity confidence": "身份置信度",
  "Identity support only": "仅支持身份",
  "If you need more reviewable candidates, these are the first levers worth trying.": "如果你需要更多可查看的候选人，可以先试试这几个方法。",
  "Illustrative candidate review": "候选人评估示例",
  "Import": "导入",
  "Import candidates": "导入候选人",
  "Import existing candidates": "导入现有候选人",
  "Import row not found": "未找到导入行",
  "Import up to 10,000 rows and 100 columns per CSV": "每个 CSV 最多导入 10,000 行和 100 列",
  "Imports, candidate searches and drafts will appear here. You can leave a page and return to its result later.": "导入记录、候选人搜索和草稿会显示在这里。你可以离开页面，稍后再回到对应结果。",
  "in this draft’s sources.": "在此草稿的来源中。",
  "indexed candidates.": "已索引的候选人。",
  "InMail subject": "InMail 主题",
  "Interest & sharing": "兴趣与分享",
  "Interest in this role": "对该职位的兴趣",
  "Interest in this role has not been recorded.": "尚未记录对该职位的兴趣。",
  "Interface language": "界面语言",
  "AI assistant": "AI 助理",
  "Ask your AI assistant": "交给 AI 助理",
  "Ask AI assistant": "询问 AI 助理",
  "Try a different search or clear your filters.": "试试其他搜索词，或清除筛选条件。",
  "Review search brief": "确认寻访需求",
  "Paste at least 50 characters to review your search brief.": "填写至少 50 个字符，即可进入寻访需求确认。",
  "Active": "未归档",
  "Ready": "可查看",
  "Running": "处理中",
  "Issues": "需处理",
  "Archived": "已归档",
  "Ready to review": "可查看结果",
  "Review now, refining in background": "可查看初步结果，后台继续评估",
  "Unlock contacts": "解锁联系方式",
  "No pool yet": "暂无候选人",
  "Ready pool": "候选人已就绪",
  "Review later": "稍后查看",
  "Needs cleanup": "需要处理",
  "Review recommendations": "查看推荐",
  "Inspect evidence gaps": "查看待核实项",
  "Export client list": "导出客户名单",
  "Pending": "处理中",
  "Clear filters": "清除筛选",
  "Account menu": "账户菜单",
  "Interview": "面试",
  "interview": "面试中",
  "Invalid code.": "验证码无效。",
  "Invalid password.": "密码无效。",
  "I’ve kept your original file, but couldn’t finish reading it.": "我已保留你的原始文件，但未能读完。",
  "I’ve matched the columns to candidate fields. Check the sample before I save anyone.": "我已将各列匹配到候选人字段。保存任何候选人前，请先查看示例。",
  "JD": "JD",
  "JD-specific judgment": "JD 专属判断",
  "Job description": "职位描述",
  "Join the early-user group": "加入早期用户群",
  "KB · stored CV": "KB · 已存简历",
  "Keep call notes, messages and source material here. Each record keeps its original date.": "将通话笔记、消息和来源材料保存在这里。每条记录保留原始日期。",
  "Keep existing": "保留现有",
  "Keep the context behind every candidate conversation.": "保留每次候选人对话背后的背景。",
  "Keep the original requirements, candidate discussions and client material together. You can add people from your existing candidate pool.": "将原始需求、候选人讨论和客户材料放在一起。你可以从现有候选人库中添加人员。",
  "Keep this profile as market coverage unless a recruiter manually promotes it.": "除非招聘人员手动提升，否则将此档案保留为市场覆盖。",
  "Keep your candidates, client roles and recommendations connected.": "让候选人、客户职位和推荐保持关联。",
  "Build your own candidate pool": "建立自己的候选人池",
  "Build your own candidate pool, ask sharper questions against each JD, and draft client recommendations from evidence you can explain.": "建立你自己的候选人池，针对每个 JD 提出更精准的问题，并基于可解释的证据起草客户推荐。",
  "Kept in this person's record. You choose which notes to include in client material.": "保留在此人的记录中。你可以选择将哪些笔记包含在客户材料中。",
  "Language": "语言",
  "Last contact": "最近联系",
  "Latest conversation": "最近对话",
  "Launch search": "启动寻访",
  "Lead with verified public engineering evidence when available; otherwise use the strongest profile-based fit signal.": "如有可验证的公开工程证据，优先采用；否则使用基于资料的最强匹配信号。",
  "Leave this blank if the event date is unknown. The save time is recorded separately.": "如果不知道发生日期，请留空；系统会另行记录保存时间。",
  "Let’s pick up the work.": "继续开展工作吧。",
  "Limit reached": "已达上限",
  "Link candidate": "关联候选人",
  "Link candidate to a role": "将候选人与职位关联",
  "Link people from your candidate pool. Their interest, sharing permission and conversations are kept with this role.": "从候选人库中关联人员。他们的意向、分享权限和对话记录会保留在该职位下。",
  "Link this candidate to the role before requesting an assessment": "在请求评估前，先将此候选人关联到该职位",
  "Link to a role": "关联到职位",
  "LinkedIn": "LinkedIn",
  "LinkedIn copy": "LinkedIn 文案",
  "LinkedIn outreach is not ready yet": "LinkedIn 外联尚未就绪",
  "LinkedIn profile": "LinkedIn 个人资料",
  "LinkedIn resume": "LinkedIn 简历",
  "LinkedIn search usually takes 5-10 minutes": "LinkedIn 寻访通常需要 5–10 分钟",
  "Linking a person does not confirm interest or permission to share.": "关联人员并不代表已确认其意向或分享许可。",
  "Live progress": "实时进展",
  "Loading candidates…": "正在加载候选人…",
  "Loading roles…": "正在加载职位…",
  "Loading search…": "正在加载寻访…",
  "Looking at your current work…": "正在查看你目前的工作…",
  "Location": "地点",
  "Location / remote scope": "地点/远程范围",
  "Location fit": "地点匹配",
  "Location not recorded": "未记录地点",
  "Lower-priority profiles stay available for review, but Hirelix does not treat them as ready-to-contact recommendations.": "较低优先级的档案仍可查看，但 Hirelix 不会将其视为可立即联系的推荐。",
  "Main navigation": "主导航",
  "Main risk": "主要风险",
  "Make it shorter and lead with the team-building experience.": "缩短内容，并以团队建设经验开头。",
  "Manage billing": "管理账单",
  "Manage password sign-in for this account.": "管理此账户的密码登录。",
  "Manage your login, plan, usage, and outreach identity.": "管理您的登录、套餐、用量和外联身份。",
  "Manual review notes": "人工审核备注",
  "Mark": "标记",
  "Merge into an existing match": "合并到现有匹配",
  "Message": "消息",
  "Message your AI assistant": "给 AI 助理发消息",
  "Minimum years": "最低年限",
  "month to month": "按月",
  "Move likelihood": "跳槽可能性",
  "Must-have coverage": "必备条件覆盖率",
  "Must-have skills (one per line)": "必备技能（每行一个）",
  "My workspace": "我的工作区",
  "Name / role": "姓名 / 职位",
  "Name needs review": "姓名需要审核",
  "Names & fields": "姓名和字段",
  "Needs review": "待审核",
  "Network error while saving profile.": "保存个人资料时发生网络错误。",
  "New": "新建",
  "new": "新候选人",
  "New candidate pool": "新建候选人库",
  "New conversation": "新建对话",
  "New password": "新密码",
  "New search": "新建搜索",
  "New Search": "新建搜索",
  "Next": "下一步",
  "Next action": "下一步操作",
  "Next import page": "下一个导入页面",
  "Next page": "下一页",
  "Next step": "下一步",
  "Next to clarify": "待澄清",
  "No candidate submissions yet.": "尚无候选人推荐。",
  "No candidates entered the ranked pool yet.": "尚无候选人进入排名池。",
  "No candidates in this list.": "此列表中没有候选人。",
  "No candidates linked yet.": "尚未关联候选人。",
  "No charge": "不收费",
  "No confirmed recommendations yet": "尚无已确认的推荐",
  "No conflicting populated fields. Imported source records will be retained.": "没有冲突的已填写字段。导入的源记录将保留。",
  "No conversation recorded yet.": "尚未记录对话。",
  "No credit card": "无需信用卡",
  "No current role recorded": "未记录当前职位",
  "No CV or profile source added.": "未添加简历或档案来源。",
  "No CV selected": "未选择简历",
  "No CV selected for this person.": "未为此人选择简历。",
  "No education details available.": "暂无教育详情。",
  "No eligible dated records in this period. The update will say that no activity was recorded.": "此期间无符合条件的带日期记录。进展汇报将说明未记录任何活动。",
  "No exact identity match found": "未找到完全匹配的身份",
  "No imported CV for this person yet.": "尚未为此人导入简历。",
  "No lower-priority breakdown is available for this search yet.": "此搜索暂无较低优先级明细。",
  "No matching candidates": "无匹配候选人",
  "No matching profiles were found": "未找到匹配的候选人资料",
  "No matching roles": "无匹配职位",
  "No material profile-specific risk was identified. Confirm availability during outreach.": "未发现与档案相关的重大风险。在联系时确认可到岗情况。",
  "No material risk recorded": "未记录重大风险",
  "No open questions recorded.": "未记录待解决问题。",
  "No outreach-ready candidates found": "未找到可外联的候选人",
  "No previous search update delivery recorded.": "未记录过往进展汇报发送情况。",
  "No private notes selected.": "未选择私人备注。",
  "No profiles currently have enough evidence for a confirmed recommendation. Open Verify first to inspect specific gaps, or Full pool to see all decisions.": "目前没有档案有足够证据支持确认推荐。请先打开“核验”查看具体缺口，或打开“完整人才库”查看所有决定。",
  "No readable text was found in this Word document. Upload a text CV.": "此 Word 文档中未找到可读文本。请上传文本简历。",
  "No reliable movement signal appears in the profile. Confirm motivation during first contact.": "档案中未出现可靠的异动信号。首次联系时确认求职动机。",
  "No sample value": "无示例值",
  "No shortlists match this view.": "没有候选名单匹配此视图。",
  "No submissions match this view.": "没有候选人推荐匹配此视图。",
  "No tasks yet.": "暂无任务。",
  "No work history available.": "暂无工作经历。",
  "not confirmed": "未确认",
  "Not confirmed": "未确认",
  "Not recorded": "未记录",
  "Not recorded yet.": "尚未记录。",
  "Not saved": "未保存",
  "Not scheduled": "未安排",
  "Not specified": "未指定",
  "Notes are private by default. Only the notes you select below are sent to the draft writer. Original files and contact details are excluded.": "备注默认私密。只有您选中的备注会用于生成草稿；原始文件和联系方式不会包含在内。",
  "Nothing is sent to the client.": "不会向客户发送任何内容。",
  "Now": "现在",
  "of": "/",
  "One hard filter per line, only if it changes who should be sourced.": "每行一个硬性筛选条件，仅当影响应寻访人选时填写。",
  "One item per line.": "每行一项。",
  "One JD at a time": "一次一个JD",
  "One more step to build your sourcing brief.": "还差一步即可生成人才寻访简报。",
  "One redemption per account. Access ends automatically after 30 days.": "每个账户仅可兑换一次。30 天后访问自动结束。",
  "Only failed tasks can be retried": "仅失败任务可重试",
  "Only records that happened within the reporting period can be included": "仅可纳入报告期内发生的记录",
  "Only the files listed here were selected for this submission. Review and download each before sharing. PDF and DOCX exports contain the written recommendation only.": "仅此处列出的文件被选中用于本次候选人推荐。分享前请逐一查看并下载。PDF 和 DOCX 导出仅包含书面推荐。",
  "Onsite": "现场",
  "Open": "开放",
  "Open a candidate to review the recommendation, evidence, risk, and outreach.": "打开候选人，查看推荐、证据、风险和触达内容。",
  "Open a source to check why a person was found. Similarity does not establish fit for a role.": "打开来源，查看此人为何被找到。相似度并不代表适合某个职位。",
  "Open agent": "打开 AI 助理",
  "Open any task to see the brief, the current stage, and when to come back. You do not need to keep the page open.": "打开任意任务，查看简报、当前阶段和何时回来。无需保持页面打开。",
  "Open candidate": "打开候选人",
  "Open each profile to check the evidence gaps before deciding whether to contact them.": "打开每个档案，检查证据缺口，再决定是否联系他们。",
  "Open each recommended profile for supporting evidence and outreach copy.": "打开每个推荐档案，查看支持性证据和触达文案。",
  "Open LinkedIn profile": "打开 LinkedIn 个人资料",
  "Open LinkedIn Profile": "打开 LinkedIn 个人资料",
  "Open navigation": "打开导航",
  "Open outreach editor": "打开触达编辑器",
  "Open profile": "打开档案",
  "Open source": "打开来源",
  "Open task": "打开任务",
  "Open the document preparation page to continue": "打开文档准备页面以继续",
  "Open work": "打开作品",
  "Open your agent": "打开你的 AI 助理",
  "Open your private agent": "打开你的私人 AI 助理",
  "Open your workspace": "打开你的工作区",
  "Opening billing...": "正在打开账单...",
  "Opening candidate…": "正在打开候选人…",
  "Opening checkout...": "正在打开结账...",
  "Opening import…": "正在打开导入…",
  "Opening role…": "正在打开职位…",
  "Opening workbench...": "正在打开工作台…",
  "Opening your conversation…": "正在打开你的对话…",
  "Opening your file…": "正在打开你的文件…",
  "Optional: audience, emphasis, tone or desired length.": "可选：受众、侧重点、语气或期望长度。",
  "Or": "或",
  "or continue with email": "或使用邮箱继续",
  "Original files are retained with the imported records. Scanned PDF images need a text version.": "原始文件会与导入记录一并保留。扫描的 PDF 图像需要文本版本。",
  "Original JD": "原始JD",
  "Original job description": "原始职位描述",
  "Original Job Description": "原始职位描述",
  "Original note or message": "原始备注或消息",
  "Original source": "原始来源",
  "Original:": "原始：",
  "Outreach angle": "外联角度",
  "Outreach approval queue": "外联审批队列",
  "Outreach context": "外联背景信息",
  "Outreach drafts": "外联草稿",
  "Outreach drafts will sign off with your name. Client company details remain confidential.": "外联草稿将以你的名义署名。客户公司详情将保密。",
  "Outreach identity": "外联身份",
  "Outreach not prepared by default": "默认不准备外联内容",
  "Outreach-ready shortlist": "可外联候选名单",
  "Overall ranks the candidate pool; the three dimensions explain why.": "综合评分对候选人池进行排名；三个维度解释原因。",
  "Overall score": "综合评分",
  "Page": "页面",
  "Paid action": "付费操作",
  "Password": "密码",
  "Password enabled": "密码已启用",
  "Password login is optional. Email code sign-in remains available.": "密码登录为可选。邮箱验证码登录仍然可用。",
  "Paste a client role": "粘贴客户职位",
  "Paste a real client job description here...": "在此粘贴真实客户职位描述...",
  "Paste at least 50 characters to continue.": "至少粘贴 50 个字符才能继续。",
  "Paste one client JD": "粘贴一个客户 JD",
  "Paste one real client role.": "粘贴一个真实客户职位。",
  "Paste one real JD": "粘贴一个真实 JD",
  "Paste the client role and confirm the brief.": "粘贴客户职位并确认职位简报。",
  "Paste the full client job description here...": "在此粘贴完整的客户职位描述...",
  "Paste the original JD. You can refine the working requirements below.": "粘贴原始 JD。你可以在下方完善工作要求。",
  "Pause": "暂停",
  "paused": "已暂停",
  "Paused. Scheduled drafts will not be prepared.": "已暂停。不会准备定时草稿。",
  "People, conversations and context, kept together.": "候选人资料、沟通记录和背景信息，集中管理。",
  "Permission to share for this role": "此职位的分享许可",
  "Personalized outreach": "个性化外联",
  "Phone": "电话",
  "Pick the roles that need review, outreach, or cleanup today.": "选择今天需要审核、外联或清理的职位。",
  "Placed": "已入职",
  "placed": "已入职",
  "Plan and usage": "套餐与用量",
  "Pool diagnostics and widening levers": "人才库诊断与拓宽手段",
  "Pool note": "人才库备注",
  "Pool Review": "人才库审核",
  "Popular": "热门",
  "Possible duplicate": "可能重复",
  "Prefer monthly?": "偏好按月？",
  "Preliminary": "初步",
  "Prepare": "准备",
  "Prepare a candidate submission": "准备候选人推荐",
  "Prepare a search update": "准备进展汇报",
  "Prepare a submission": "准备推荐",
  "Prepare candidate submission": "准备候选人推荐",
  "Prepare candidate submissions and keep a record of what you share.": "准备候选人推荐，并记录你分享的内容。",
  "Prepare client material": "准备客户材料",
  "Prepare draft": "准备草稿",
  "Prepare revision": "准备修订",
  "Prepare search update": "准备进展汇报",
  "Prepare submission": "准备候选人推荐",
  "Preparing column mapping for your review": "正在准备列映射供您审阅",
  "Preparing revision…": "正在准备修订…",
  "Preparing rows…": "正在准备行…",
  "Preparing your draft…": "正在准备您的草稿…",
  "Preparing your reply": "正在准备回复",
  "Preparing your revision": "正在准备您的修订",
  "Preparing your role...": "正在准备您的职位...",
  "Preview one client role with a real AI sourcing budget.": "预览一个配有真实 AI 人才寻访预算的客户职位。",
  "Previous": "上一个",
  "Previous import page": "上一个导入页面",
  "Previous page": "上一页",
  "Previous requirements": "先前要求",
  "Pricing": "定价",
  "Priority": "优先级",
  "Privacy Policy": "隐私政策",
  "Privacy Policy for Hirelix.": "Hirelix 隐私政策。",
  "Privacy Policy | Hirelix": "隐私政策 | Hirelix",
  "Your private candidate pool": "你的私人候选人池",
  "Private JD handoff": "私密 JD 交接",
  "Private note": "私密备注",
  "Private to your account": "仅你的账户可见",
  "Professional": "专业",
  "Professional summary": "职业概述",
  "Profile": "个人资料",
  "Profile evidence": "个人资料证据",
  "Profile fit reviewed": "个人资料匹配已审核",
  "Profile saved.": "个人资料已保存。",
  "Profile URL": "个人资料 URL",
  "profiles reviewed.": "份资料已审阅",
  "Proof:": "证据：",
  "Q.": "问.",
  "Questions": "问题",
  "Questions about your private agent": "关于你的私人 AI 助理的问题",
  "Questions to follow up": "待跟进问题",
  "Queued": "已排队",
  "queued": "排队中",
  "Rank": "排名",
  "Rank #": "排名 #",
  "Ranked candidate pool": "已排名候选人池",
  "Ranked candidates": "已排序候选人",
  "Ranking is based on profile facts. Research this candidate when they are worth deeper review.": "排名基于个人资料事实。当该候选人值得深入审阅时，再对其进行调研。",
  "Reach out first": "先联系",
  "Read original note before including it": "包含前请阅读原始备注",
  "Read supporting evidence": "阅读支持性证据",
  "Reading JD...": "正在读取 JD...",
  "Reading the CV into a candidate draft": "正在读取简历并生成候选人草稿",
  "Reading your conversation and workspace": "正在读取您的对话和工作区",
  "Ready for your review": "待您审阅",
  "Ready to act": "准备就绪",
  "Recent activity": "最近活动",
  "Recent conversations": "最近对话",
  "Recent imports": "最近导入",
  "Recipient, channel, and any relevant context": "收件人、渠道及相关背景信息",
  "Recommendation": "推荐",
  "Recommendation briefs": "候选人推荐材料",
  "Recommendation drafts": "推荐草稿",
  "Recommended": "推荐",
  "Recommended (": "推荐（",
  "Recommended order": "推荐顺序",
  "Record": "记录",
  "Record actual submission": "记录实际发送",
  "Record an actual submission": "记录一次实际候选人推荐",
  "Record submission": "记录候选人推荐",
  "Record type": "记录类型",
  "Record when you actually shared this document, not a future date": "记录实际分享此文档的日期，而非未来日期",
  "records": "记录",
  "Recruiter details": "招聘人员详情",
  "Recruiter feedback": "招聘人员反馈",
  "Recruiter identity": "招聘人员身份",
  "Recruiter note": "招聘人员备注",
  "Redeem": "兑换",
  "Redeem beta access": "兑换 Beta 访问权限",
  "Redeeming...": "兑换中...",
  "Refine & expand": "优化并扩展",
  "Refine & Retry": "优化并重试",
  "Refine JD": "优化 JD",
  "Refine JD and search again": "优化JD并重新搜索",
  "Refresh": "刷新",
  "Refund Policy": "退款政策",
  "Refund Policy for Hirelix.": "Hirelix 退款政策。",
  "Refund Policy | Hirelix": "退款政策 | Hirelix",
  "Regenerate": "重新生成",
  "Regenerate with research": "结合调研重新生成",
  "rejected": "已排除",
  "Relevant based on the current profile fit and risk signals.": "基于当前画像匹配度与风险信号，相关。",
  "Remember candidates": "记住候选人",
  "Remote": "远程",
  "Remote, US, New York, etc.": "远程、美国、纽约等",
  "Remove attachment": "移除附件",
  "Remove candidate from conversation": "从新对话移除候选人",
  "Remove role from conversation": "从新对话移除职位",
  "Renewal": "续费",
  "Reopen": "重新打开",
  "Repeat password": "重复密码",
  "replied": "已回复",
  "Reply": "回复",
  "Reply by email": "邮件回复",
  "Reply to the clarification, or leave blank and launch...": "回复澄清内容，或留空并启动...",
  "Reporting period": "汇报周期",
  "Request noted. I will reply with the next step.": "请求已记录。我会回复下一步。",
  "Required skills": "必备技能",
  "Rescore": "重新评分",
  "Research": "调研",
  "Research available": "调研可用",
  "Research basis": "调研依据",
  "Research candidate": "调研候选人",
  "Research evidence": "调研证据",
  "Research pending": "调研待处理",
  "Research ready": "调研已就绪",
  "research runs left this cycle": "本周期剩余调研次数",
  "Research sources": "调研来源",
  "Research this candidate when they are worth a closer look.": "当该候选人值得深入了解时，对其进行调研。",
  "Research this candidate when this profile is worth a closer look.": "当该画像值得深入了解时，调研该候选人。",
  "Research-backed proof is available for the client brief or outreach.": "有调研支撑的证明材料可用于客户简报或外联。",
  "Resend code": "重新发送验证码",
  "Response times": "响应时间",
  "Resume": "简历",
  "Retry revision": "重试修订",
  "Retry task": "重试任务",
  "Retry this search": "重试本次搜索",
  "Retrying...": "正在重试...",
  "Review": "检查",
  "Review & save": "检查并保存",
  "Review extraction notes": "核对提取备注",
  "Review a proposed revision before replacing your draft. Your previous version is kept.": "在替换草稿前检查提议的修订。您的上一版本会保留。",
  "Review and edit the agent’s recommendation draft before sharing.": "分享前查看并编辑 AI 助理的推荐草稿。",
  "Review column mapping": "检查列映射",
  "Review conversation record": "检查对话记录",
  "Review duplicate": "检查重复项",
  "Review fields": "检查字段",
  "Review file": "检查文件",
  "Review first": "先检查",
  "Review fit for this role": "检查与该职位的匹配度",
  "Review imported candidate": "检查导入的候选人",
  "Review merged candidate": "检查合并后的候选人",
  "Review new role": "检查新职位",
  "Related client records": "相关客户记录",
  "These records will be saved with this role.": "这些记录会随职位一起保存。",
  "Event time not recorded": "未记录发生时间",
  "Review proposed revision": "检查提议的修订",
  "Review role fit": "检查职位匹配度",
  "Review role requirements": "审阅职位要求",
  "Review saved profiles": "检查已保存的资料",
  "Review the fields and possible duplicates before saving to your candidate pool.": "保存到候选人库前，请检查字段和可能的重复项。",
  "Review the proposed requirements before applying": "应用前请检查提议的要求",
  "Review the role details before saving": "保存前请检查职位详情",
  "Review this record before adding it": "添加前请检查此记录",
  "Review updated requirements": "查看更新后的要求",
  "Review, copy, then mark progress.": "查看、复制，然后标记进展。",
  "Reviewing candidates": "正在审阅候选人",
  "Reviewing profiles now": "正在审阅资料",
  "Reviewing saved profiles": "正在查看已保存的个人资料",
  "Reviewing your candidates now.": "正在查看您的候选人。",
  "Revise a draft": "修改草稿",
  "Revise with your AI assistant": "与 AI 助理一起修改",
  "Revising your saved draft": "正在修改已保存的草稿",
  "Revision applied. The earlier text is available in version history.": "修改已应用。较早文本可在版本历史中查看。",
  "Risk to verify": "需核实的风险",
  "Risk:": "风险：",
  "Role": "职位",
  "Role assessment": "职位匹配判断",
  "Role evidence": "职位依据",
  "Role Fit": "职位匹配度",
  "Role sections": "职位部分",
  "Role status": "职位状态",
  "Role title": "职位名称",
  "Role title or JD snippet": "职位名称或JD片段",
  "Role title or job description snippet": "职位名称或职位描述片段",
  "roles": "职位",
  "Roles": "职位",
  "rows": "行",
  "Run a real preview before you pay.": "付费前先体验真实流程。",
  "Run expansion": "运行扩展",
  "Run one real role free": "免费运行一个真实职位",
  "running": "处理中",
  "Sample role": "示例职位",
  "Save candidate": "保存候选人",
  "Save profile": "保存个人资料",
  "Save record": "保存记录",
  "Save relationship": "保存关系",
  "Save role": "保存职位",
  "Save the context that usually disappears between assignments.": "保存通常会在任务之间丢失的上下文。",
  "Save your current edits before revising.": "修改前请先保存当前编辑。",
  "Saved": "已保存",
  "Saved searches": "已保存的搜索",
  "Saved to your workspace": "已保存到你的工作区",
  "Saved with this draft · Role version": "已随此草稿保存 · 职位版本",
  "Saving your message…": "正在保存你的消息…",
  "Saving…": "正在保存…",
  "Scan the full ranked pool with lower-priority context preserved.": "扫描完整排名候选人池，并保留较低优先级的上下文。",
  "Scorecard": "评分卡",
  "Search": "搜索",
  "Search accepted": "已接收寻访",
  "Search by candidate, client or role": "按候选人、客户或职位搜索",
  "Search by role or client": "按职位或客户搜索",
  "Search candidates": "搜索候选人",
  "Search method": "搜索方式",
  "Search needs calibration": "搜索需要校准",
  "Search people, companies or your notes": "搜索候选人、公司或你的笔记",
  "Search risks": "搜索风险",
  "Search roles": "搜索职位",
  "Search update": "进展汇报",
  "Search update ·": "进展汇报 ·",
  "Search your candidate pool": "搜索你的候选人池",
  "Search your candidates": "搜索你的候选人",
  "What would you like to work on?": "今天想处理什么？",
  "Ask a question, paste a JD, or add a file. I'll follow your lead.": "直接提问、粘贴 JD，或添加文件。我会按你的需求来。",
  "You can return to this page to review the result. Your original file is saved.": "你可以回到此页查看结果，原始文件已保存。",
  "Nothing needs attention right now.": "目前没有需要处理的任务。",
  "Earlier work": "更早的工作",
  "Discard your unsaved candidate changes?": "放弃尚未保存的候选人修改？",
  "Discard your unsaved role changes?": "放弃尚未保存的职位修改？",
  "Discard this unsaved record?": "放弃这条尚未保存的记录？",
  "You have unsaved edits from a previous visit.": "上次离开时有尚未保存的修改。",
  "Restore edits": "恢复修改",
  "Discard edits": "放弃修改",
  "This conversation already has an unsent draft. Replace it?": "这个对话已有尚未发送的草稿，确定替换吗？",
  "Delete this candidate and their source records? Existing client documents and conversations remain as historical work. This cannot be undone.": "确定删除这位候选人及其来源记录？现有客户材料和对话将作为历史保留。此操作无法撤销。",
  "Delete this sourcing task and all its candidates?": "确定删除这项寻访任务及其候选人吗？",
  "Searching your indexed candidate records": "正在搜索您已索引的候选人记录",
  "Secure": "安全",
  "Secure sign in": "安全登录",
  "See a search example": "查看搜索示例",
  "Select a candidate to see their profile, original notes, and the roles you have discussed with them.": "选择候选人，查看其个人资料、原始笔记以及你与其讨论过的职位。",
  "Select a client role before preparing this document.": "准备此文档前，请选择客户职位。",
  "Select a role when your conversation relates to a client assignment.": "当对话涉及客户委托时，选择职位。",
  "Select all": "全选",
  "Select candidates to see their supporting notes.": "选择候选人，查看其支持性备注。",
  "Select fewer source records for this draft": "为此草稿选择更少的来源记录",
  "Select the candidate or role where this record belongs.": "请选择此记录所属的候选人或职位。",
  "selected": "已选",
  "Selected": "已选择",
  "selected notes": "已选备注",
  "Selling evidence is separated from identity support so recruiters do not overstate the proof.": "卖点证据与身份佐证分开，以免招聘人员夸大证明。",
  "Send a valid JSON request": "发送有效的 JSON 请求",
  "Send message": "发送消息",
  "Sending request...": "正在发送请求...",
  "Sending...": "正在发送...",
  "Separate skills or areas of expertise with commas.": "用逗号分隔技能或专业领域。",
  "Service providers": "服务提供商",
  "Set password": "设置密码",
  "Settings": "设置",
  "Share": "分享",
  "Share client view": "分享客户视图",
  "Sharing confirmed": "分享已确认",
  "Sharing declined": "分享已拒绝",
  "Sharing declined — review before any submission": "分享已拒绝 — 任何候选人推荐前请先审核",
  "Sharing not confirmed": "分享未确认",
  "Sharing permission confirmed": "分享权限已确认",
  "sharing permission declined": "分享权限已拒绝",
  "sharing permission not confirmed": "分享权限未确认",
  "Sharing permission not confirmed": "分享权限未确认",
  "Sharing permission:": "分享权限：",
  "Short bio": "简短简介",
  "Shortlist ready": "候选人池已就绪",
  "Shortlist ready now; background refinement may take 1-3 more minutes": "候选人池已就绪，后台整理可能还需 1–3 分钟",
  "Sign in": "登录",
  "Sign in and keep moving.": "登录，继续推进。",
  "Sign in to continue": "登录以继续",
  "Sign in to continue with this JD and build your sourcing brief.": "登录以继续处理此 JD 并生成人才寻访简报。",
  "Sign in to Hirelix": "登录 Hirelix",
  "Sign in to open your shortlist": "登录以打开你的候选名单",
  "Sign in to save the role": "登录以保存职位",
  "Sign in to your workspace": "登录到你的工作区",
  "Sign in with password": "使用密码登录",
  "Sign out": "退出登录",
  "Skills": "技能",
  "Skip": "跳过",
  "Skipped": "已跳过",
  "Some rows have already been saved. Start a new import to change the mapping.": "部分行已保存。要更改映射，请开始新的导入。",
  "Sort by": "排序方式",
  "Source": "来源",
  "Source claims stay separate from your notes": "来源声明与你的笔记分开保存",
  "Source material": "来源材料",
  "Source record": "来源记录",
  "Source URL (optional)": "来源URL（可选）",
  "Sources": "来源",
  "Sourcing": "人才寻访",
  "Sourcing brief": "人才寻访简报",
  "Sourcing cockpit": "人才寻访驾驶舱",
  "Specialization": "专业领域",
  "starred": "已收藏",
  "Start a subscription when you need the full client-ready brief.": "当你需要完整、可直接交付客户的简报时，再开始订阅。",
  "Start Starter": "开通 Starter 套餐",
  "Start with a client JD": "从客户 JD 开始",
  "Start with a client’s JD.": "从客户JD开始。",
  "Start with the people you know.": "从你认识的人开始。",
  "Start with the real JD. Hirelix turns it into a brief, screens technical profiles, and opens a shortlist workbench when candidates are ready.": "从真实JD开始。Hirelix 会将其转化为简报，筛选技术档案，并在候选人准备好后打开入围名单工作台。",
  "Start with this JD": "以此JD开始",
  "Start with your private AI assistant": "从你的私人 AI 助理开始",
  "Started": "已开始",
  "Starter beta access": "Starter 测试版访问权限",
  "Starting assessment…": "正在开始评估…",
  "Starting with your existing candidates?": "从你现有的候选人开始？",
  "Starting…": "正在开始…",
  "Status": "状态",
  "Subject copied": "主题已复制",
  "Submissions": "候选人推荐",
  "submissions recorded": "已记录候选人推荐",
  "Submit": "提交",
  "Submitted": "已提交",
  "submitted": "已提交",
  "Submitted copy": "已提交副本",
  "Subscription": "订阅",
  "Subscription active": "订阅有效",
  "Subscriptions renew automatically until canceled.": "订阅会自动续订，直至取消。",
  "Subscriptions, renewals, and cancellations": "订阅、续订和取消",
  "suggestions from": "建议来自",
  "Support email": "支持邮箱",
  "Support:": "支持：",
  "support@hirelix.online": "support@hirelix.online",
  "Supporting conversation or record": "佐证对话或记录",
  "Supporting experience": "佐证经验",
  "Supporting notes": "佐证备注",
  "Targeted profile scan budget": "定向画像扫描额度",
  "Targeted profile scans are AI sourcing budget, not a guaranteed final candidate count. Hirelix observes the pool, adjusts sourcing angles, dedupes useful profiles, and ranks the strongest candidates found within your plan budget.": "定向人才画像扫描属于 AI 人才寻访预算，并非保证的最终候选人数量。Hirelix 会观察人才池、调整人才寻访角度、对有用人才画像去重，并在你的方案预算内对找到的最强候选人进行排序。",
  "targeted scans left this cycle": "本周期剩余定向扫描次数",
  "Tasks": "任务",
  "Tasks and notifications": "任务与通知",
  "Technical fit": "技术匹配度",
  "Technical Fit": "技术匹配度",
  "Terms of Service": "服务条款",
  "Terms of Service for Hirelix.": "Hirelix 服务条款。",
  "Terms of Service | Hirelix": "服务条款 | Hirelix",
  "That code did not work. Please check the email and try again.": "该验证码无效。请检查邮件后重试。",
  "The agent starts from your knowledge of people and helps you make a defensible decision for each client role.": "AI 助理会从你对人选的了解出发，帮助你为每个客户职位做出有依据的决策。",
  "The agent works from your JD, the people you chose to remember, and the evidence you can actually defend.": "AI 助理会依据你的 JD、你选择记住的人选，以及你真正能站得住脚的证据来开展工作。",
  "The assistant could not identify the requested role. Retry with a role selected.": "AI 助理无法识别所请求的职位。请选择职位后重试。",
  "The assistant returned an incomplete answer. Your input is saved; retry the task.": "AI 助理返回了不完整的回答。你的输入已保存；请重试该任务。",
  "The assistant returned an unavailable candidate or role. Retry the reply.": "AI 助理返回了不可用的候选人或职位。请重试回复。",
  "The assistant returned an unavailable source. Retry the reply.": "AI 助理返回了不可用的来源。请重试回复。",
  "The assistant's answer did not include the required evidence and structure. Retry this task.": "AI 助理的回答未包含所需的证据和结构。请重试此任务。",
  "The candidate is no longer linked to this role": "该候选人已不再与此职位关联",
  "The CSV could not be read. Check that rows use a consistent number of columns and quoted fields are closed.": "无法读取 CSV。请检查各行使用的列数是否一致，以及带引号的字段是否已闭合。",
  "The draft omitted or mixed up a selected candidate. Retry this task.": "草稿遗漏或混淆了所选候选人。请重试此任务。",
  "The new passwords do not match.": "新密码不一致。",
  "The next run keeps this JD, spends targeted scan budget, and uses your feedback to adjust the sourcing lanes before recall.": "下一次运行将保留此 JD，消耗定向扫描额度，并在召回前根据你的反馈调整人才寻访渠道。",
  "The original file has been saved. Retry the same task to continue without creating another import.": "原始文件已保存。重试同一任务即可继续，不会创建新的导入。",
  "The original JD is preserved. Review the complete requirements below; accepting saves a new version and the original feedback.": "原始 JD 已保留。请查看下方完整要求；接受后将保存新版本和原始反馈。",
  "The people you know become lasting recruiting intelligence.": "你认识的人会沉淀为持久的招聘情报。",
  "The proposed mapping referenced an unknown column. Retry the import.": "映射方案引用了未知列。请重试导入。",
  "The ranked candidate pool is still growing as more recalled profiles are reviewed...": "随着更多召回的画像得到审阅，排名候选人池仍在扩大……",
  "The record association changed. Start a new record from the correct profile.": "记录关联已更改。请从正确的资料页新建记录。",
  "The role or candidate changed during the assessment. Review the changes and run it again.": "评估期间职位或候选人发生了变化。请查看变更并重新运行。",
  "The role or candidate changed while this assessment was being prepared. Review the changes and run it again.": "准备此评估时，职位或候选人已更改。请查看更改并重新运行。",
  "The role or profile has changed since this review.": "自本次审阅以来，职位或画像已发生变化。",
  "The role’s JD and working requirements, plus the candidate information shown here and your selected notes.": "该职位的 JD 与工作要求，以及此处显示的候选人信息和您选中的备注。",
  "The selected candidates changed. Prepare a new draft.": "所选候选人已变更。请重新准备草稿。",
  "The source changed while this task was running. Review the latest information and prepare it again.": "此任务运行期间来源发生了变化。请查看最新信息并重新准备。",
  "The submitted copy is preserved": "提交的副本已保留",
  "There is too much source material for one reply. Start a conversation with a specific candidate or role.": "一次回复的源材料过多。请针对特定候选人或职位开始对话。",
  "These fictional, anonymized profiles show the review format only. Run your own role when you want Hirelix to build a real ranked candidate pool.": "这些虚构、匿名的资料仅展示审阅格式。若希望 Hirelix 构建真实的候选人排名池，请运行你自己的职位。",
  "These reasons are already usable for review. Hirelix may refine the ranking and rationale as richer profile data comes in.": "这些理由已可供审阅。随着更丰富的画像数据到来，Hirelix 可能会优化排名和理由。",
  "These tasks are still running in the background.": "这些任务仍在后台运行。",
  "This 30-day Starter access does not renew automatically.": "此 30 天 Starter 访问权限不会自动续订。",
  "This candidate has extensive source material that needs indexing first. Retry after indexing completes.": "该候选人有大量源材料需要先建立索引。索引完成后重试。",
  "This candidate is not linked to a role yet. Their profile stays available between assignments.": "该候选人尚未关联职位。其画像在任务间隔期间仍可查看。",
  "This CSV preview is not ready": "此 CSV 预览尚未就绪",
  "This CV contains more text than can be reviewed in one import. Split it into individual candidate documents.": "此简历包含的文本过多，无法在一次导入中审阅。请拆分为单个候选人文档。",
  "This draft can use a different language from your interface.": "此草稿可以使用与界面不同的语言。",
  "This draft changed after the revision started. Prepare a new revision using the current text; this suggestion has been kept.": "修订开始后，此草稿发生了更改。请使用当前文本准备新的修订；此建议已保留。",
  "This file was not found": "未找到此文件",
  "This import request belongs to a different file": "此导入请求属于另一个文件",
  "This is not an import task": "这不是导入任务",
  "This is the active plan and renewal state for your account.": "这是您账户的生效方案和续订状态。",
  "This item changed in another window. Reload it before saving; your edits have been kept.": "此项已在其他窗口更改。保存前请重新加载；你的编辑已保留。",
  "This item was not found": "未找到此项",
  "This keeps the workflow human-in-the-loop while still moving candidates to contacted, replied, submitted, interview, and placed.": "此流程保持人工参与，同时仍能将候选人推进至已联系、已回复、已推荐、面试和已入职。",
  "This PDF has no readable text. Scanned-image OCR is not available; upload a text PDF or DOCX.": "此 PDF 无可读文本。扫描图像 OCR 不可用；请上传文本型 PDF 或 DOCX。",
  "This proposed action was not found": "未找到此建议操作",
  "This reply was not found": "未找到此回复",
  "This request belongs to another revision": "此请求属于其他修订版本",
  "This request key belongs to another draft": "此请求密钥属于其他草稿",
  "This request key belongs to another operation": "此请求密钥属于其他操作",
  "This request key was already used for a different operation": "此请求密钥已用于其他操作",
  "This request key was already used for another message": "此请求密钥已用于其他消息",
  "This revision is not ready for this document": "此修订版本尚未准备好用于此文档",
  "This role is active.": "此职位处于活跃状态。",
  "This role is unavailable": "此职位不可用",
  "This saved message is no longer available": "此已保存消息不再可用",
  "This shortlist run didn't finish": "本次入围名单运行未完成",
  "This submitted copy is preserved. Prepare a new draft to make further changes.": "此已提交副本已保留。如需进一步更改，请准备新草稿。",
  "This submitted copy is preserved. Prepare a new draft to revise it.": "此已提交副本已保留。请准备新草稿进行修订。",
  "This upload belongs to a conversation": "此上传文件属于某个对话",
  "This upload belongs to a different conversation or message": "此上传文件属于其他对话或消息",
  "This Word document expands beyond the 30 MB processing limit": "此 Word 文档展开后超出 30 MB 的处理限制",
  "Through": "结束时间",
  "Tip: the fuller the client role, the better the ranked pool.": "提示：客户职位越完整，候选人排名池越好。",
  "Title": "标题",
  "to review": "待审核",
  "TOOLS": "工具",
  "Top relevance": "相关度最高",
  "Track this billing cycle across the work that creates real product cost.": "跟踪此计费周期内会产生实际产品成本的工作。",
  "Try again": "重试",
  "Try another name, or search by meaning for experience and past conversations.": "尝试其他名称，或按语义搜索经历和过往对话。",
  "Understanding the role": "正在梳理职位要求",
  "Unknown": "未知",
  "unknown": "未确认",
  "Unknown Company": "未知公司",
  "Unknown role": "未知职位",
  "Unknown Role": "未知职位",
  "Unsaved changes": "未保存的更改",
  "Update role review": "更新职位审核",
  "Update the password for this email login.": "更新此邮箱登录的密码。",
  "Updated": "已更新",
  "Upgrade to research selected candidates. The current ranking is based on profile fit and risk signals.": "升级后可调研所选候选人。当前排名基于资料匹配度和风险信号。",
  "Upgrade to research the candidates you choose.": "升级后可调研您选择的候选人。",
  "Upgrade to Starter": "升级至 Starter",
  "Upgrade to Starter for brief": "升级至 Starter 以获取简报",
  "Upgrade to Starter for client brief": "升级至 Starter 以获取客户简报",
  "Upgrade to Starter for client briefs": "升级至 Starter 以获取客户简报",
  "Upload & preview": "上传并预览",
  "Upload a CV or document with 100 pages or fewer": "上传不超过100页的简历或文档",
  "Upload a non-empty file up to 4 MB": "上传不超过4 MB的非空文件",
  "Upload another file": "上传另一个文件",
  "Uploading…": "上传中…",
  "Usage": "用量",
  "Usage is based on AI sourcing budget and candidate research runs you choose to start.": "用量基于 AI 人才寻访预算以及你选择启动的候选人调研次数。",
  "Use a CSV, text PDF or DOCX file": "使用 CSV、文本 PDF 或 DOCX 文件",
  "Use a private beta code to unlock Starter for 30 days. No card required.": "使用内测码解锁 Starter 30 天。无需银行卡。",
  "Use a record for this candidate and this role": "为此候选人和此职位使用一条记录",
  "Use another email": "使用其他邮箱",
  "Use at least 8 characters.": "至少使用 8 个字符。",
  "Use email code instead": "改用邮箱验证码",
  "Use Google or email to sign in without breaking the flow.": "使用 Google 或邮箱登录，不中断流程。",
  "Use imported": "使用导入内容",
  "Use password instead": "改用密码",
  "Use the full ranked pool to compare the market and recover edge cases.": "使用完整排名池对比市场并找回边界情况。",
  "Use this after you have shared the document with your client. Hirelix will preserve this copy and add the delivery to the role’s activity.": "在向客户分享文档后使用。Hirelix 将保留此副本，并将交付记录添加到职位的活动中。",
  "Use this as the recruiter-facing summary: who to lead with, why they fit, what proof is usable, and what still needs verification.": "将此作为面向招聘人员的摘要：优先推荐谁、为何合适、哪些证据可用，以及哪些仍需核实。",
  "Use your account to continue into the next candidate pool flow without losing context.": "使用你的账户继续进入下一个候选人池流程，不丢失上下文。",
  "Useful for identity corroboration, not for a technical selling claim.": "有助于身份佐证，但不适用于技术卖点。",
  "Usually around 10 minutes from submission": "提交后通常约需 10 分钟",
  "Verify before pitching": "推介前先核实",
  "Verify code": "验证验证码",
  "Verify first": "先核实",
  "Verify first (": "先核实（",
  "Verify:": "核实：",
  "Version": "版本",
  "Version history": "版本历史",
  "View all": "查看全部",
  "View JD": "查看 JD",
  "View original imported content": "查看原始导入内容",
  "View original record": "查看原始记录",
  "View saved versions": "查看已保存版本",
  "View tasks": "查看任务",
  "Want to become an early Hirelix user?": "想成为 Hirelix 的早期用户吗？",
  "We are building a private AI assistant for professional headhunters and inviting a small early-user group.": "我们正在为专业猎头打造私人 AI 助理，并邀请一小批早期用户。",
  "We couldn't send a sign-in code. Please try again.": "无法发送登录验证码。请重试。",
  "We couldn't start Google sign in. Please try again.": "无法启动 Google 登录。请重试。",
  "We sent a code to": "验证码已发送至",
  "Welcome back": "欢迎回来",
  "What a technical headhunter reviews after a client JD.": "技术猎头在收到客户 JD 后会审阅什么。",
  "What are we working on?": "我们正在处理什么？",
  "What the agent remembers, how it handles evidence, and what stays in your hands.": "AI 助理会记住什么、如何处理证据，以及哪些仍由你掌控。",
  "What the draft can use": "草稿可用的内容",
  "What to verify before outreach": "联系前需核实什么",
  "What would you like to change?": "您想更改什么？",
  "When it happened": "发生时间",
  "When you shared it": "分享时间",
  "Who in my candidate pool might fit this new client JD?": "我的候选人池里，谁可能适合这份新的客户 JD？",
  "Who received it and how": "接收人及方式",
  "Who you are contacting": "你正在联系谁",
  "Who owns this candidate pool?": "这个候选人池归谁所有？",
  "Why / risk": "原因 / 风险",
  "Why contact this person": "为何联系此人",
  "Why here": "为何在此",
  "Why not higher": "为何不更靠前",
  "Why profiles landed lower": "为何档案排名较低",
  "Why this candidate": "为何是这位候选人",
  "Why this is not higher": "为何这项不更靠前",
  "Will it make up weekly progress?": "它会编造工作进展吗？",
  "words": "字数",
  "Work email": "工作邮箱",
  "Work email for preview reply": "用于预览回复的工作邮箱",
  "Work history": "工作经历",
  "Work History": "工作经历",
  "Work model": "工作模式",
  "Work model fit": "工作模式匹配度",
  "Work on a client role": "处理客户职位",
  "Working on": "正在处理",
  "Working on your request…": "正在处理您的请求…",
  "Working requirements": "工作要求",
  "Workspace": "工作台",
  "Worth reviewing": "值得审阅",
  "years experience": "年经验",
  "You": "你",
  "You can leave the task page after launch; Hirelix keeps building the candidate pool.": "启动后你可以离开任务页面；Hirelix 会继续构建候选人池。",
  "You can leave this page and return.": "你可以离开此页面并返回。",
  "You can leave this page. This import and its original file will remain available in Tasks.": "你可以离开此页面。本次导入及其原始文件仍可在“任务”中找到。",
  "You've reached this month's client role allowance. Your next cycle will reset automatically.": "你已达到本月客户职位额度。下个周期将自动重置。",
  "You've reached this month's targeted profile scan allowance. Your next cycle will reset automatically.": "你已达到本月定向人才画像扫描额度。下个周期将自动重置。",
  "You've used your free client-role preview. Start a subscription to keep sourcing.": "你已使用免费的客户职位预览。订阅后可继续人才寻访。",
  "you@company.com": "you@company.com",
  "Your assignments, with the requirements and conversations behind them.": "你的任务，以及其背后的需求和对话。",
  "Your candidate pool stays yours": "你的候选人池始终归你所有",
  "Your candidate pool is ready to review": "你的候选人池已可查看",
  "Your candidates have not been indexed yet. Check import and indexing tasks, or use name and field search.": "你的候选人尚未建立索引。请检查导入和索引任务，或使用姓名和字段搜索。",
  "Your candidates, your roles, and the work you prepare for clients.": "你的候选人、你的职位，以及你为客户准备的工作。",
  "Your client role": "你的客户职位",
  "Your request is saved. You can leave and return here for progress and the completed draft.": "你的请求已保存。你可以离开，返回此页面查看进度和完成后的草稿。",
  "Your imports will appear here so you can resume a review.": "你的导入将显示在这里，以便你继续查看。",
  "Your JD": "你的 JD",
  "Your JD is ready": "你的 JD 已就绪",
  "Your JD is saved": "你的 JD 已保存",
  "Your JD stays attached after sign in.": "登录后你的 JD 仍会保持关联。",
  "Your JD stays attached while you build the sourcing brief.": "构建人才寻访简报时，你的 JD 会保持关联。",
  "Your local time. Leave blank if unknown; adding a record does not imply it happened today.": "你的本地时间。未知可留空；添加记录不代表发生在今天。",
  "Your name": "你的姓名",
  "Your notes for this role": "你对此职位的备注",
  "Your own recruiting intelligence, available across roles.": "你自己的招聘情报，可跨职位使用。",
  "Your people and observations": "你的人员与观察记录",
  "Your private AI assistant and candidate workspace are available after sign-in. These plans govern the existing profile search and research capacity.": "登录后即可使用你的私人 AI 助理和候选人工作台。这些方案决定现有的候选人档案搜索与研究额度。",
  "Your private agent for": "你的私人 AI 助理，用于",
  "YOUR PRIVATE AI ASSISTANT": "你的私人 AI 助理",
  "Your private note": "你的私人备注",
  "Your recruiting specialization. Helps Hirelix frame outreach from a credible, relevant angle.": "你的招聘专长。帮助 Hirelix 从可信且相关的角度构思外联。",
  "Your saved conversations will appear here.": "你保存的对话将显示在这里。",
  "Your search has been accepted.": "你的寻访已受理。",
  "Your work can start here.": "你可以从这里开始工作。",
  "Your work continues here, including tasks started in the assistant.": "你的工作在此继续，包括在 AI 助理中开始的任务。",
  "Your work email": "您的工作邮箱",
  "· Added": "· 已添加",
  "· Candidate import": "· 候选人导入",
  "· Happened": "· 已发生",
  "· Research this candidate when you need citable proof.": "· 需要可引用的依据时，研究该候选人。",
  "· Updated": "· 已更新",
  "← Back to homepage": "← 返回首页",
  "⌘ / Ctrl + Enter to send": "⌘ / Ctrl + Enter 发送",
  "All": "全部",
  "Drafts": "草稿",
  "Overview": "概览",
  "Conversations & sources": "沟通与来源",
  "Related roles": "关联职位",
  "Brief": "职位要求",
  "Activity": "动态",
  "Confirmed priorities": "已确认的重点",
  "Flexible requirements": "可放宽的要求",
  "Still to clarify": "待确认事项",
  "Update password": "更新密码",
  "Current password is not correct.": "当前密码不正确。",
  "A password is already set. Use change password instead.": "已设置密码，请使用修改密码。",
  "Could not update the password. Please try again.": "无法更新密码，请重试。",
  "Password updated.": "密码已更新。",
  "Password set. You can now sign in with email and password.": "密码已设置。现在可以使用邮箱和密码登录。",
  "Give your agent the role you are working on and the requirements that actually matter.": "告诉 AI 助理你正在处理的职位，以及真正重要的要求。",
  "Save people and your own observations once, even when a particular search is over.": "保存候选人和你的观察记录，职位结束后仍可继续使用。",
  "The agent explains who might fit this JD, which evidence supports that view, and what remains unverified.": "AI 助理会说明谁可能适合这份 JD、依据是什么，以及哪些信息尚待核实。",
  "Turn the available evidence into a recommendation brief you can edit before sharing.": "根据现有依据生成推荐材料，并在分享前编辑。",
  "Keep candidate context and your own notes beyond a single assignment.": "候选人背景和你的备注可以跨职位保留。",
  "JD as context": "以 JD 为背景",
  "Bring the client's actual role. A person can fit one JD and miss another.": "录入客户的真实职位。同一位候选人可能适合一个职位，却不适合另一个。",
  "Get a direct answer about saved people, evidence gaps, and the role in front of you.": "直接询问已保存的人选、证据缺口和当前职位。",
  "Generate and revise a weekly client update from what is recorded, with no invented activity.": "根据已记录的进展生成和修改给客户的定期更新，不虚构活动。",
  "The current sourcing engine remains available to discover people to review and remember.": "现有的人才寻访能力可用于发现值得进一步了解并保存的人选。",
  "Evidence and uncertainty": "依据与待确认信息",
  "Keep recruiter notes separate from source claims, and call out what still needs verification.": "区分你的备注与来源陈述，并明确哪些信息还需核实。",
  "Yours. You decide whom to save and what private observations the agent can use across roles.": "归你所有。你决定保存哪些人，以及 AI 助理可以跨职位使用哪些私人观察。",
  "Yes. Saved recruiter notes and imported search evidence retain their source context, so uncertain claims can stay uncertain.": "可以。你的备注和导入的寻访依据会保留各自来源，不确定的说法仍标为待核实。",
  "Yes. Existing JD search remains available when you need to discover people outside your private memory.": "可以。当候选人池外需要更多人选时，你仍可使用现有的 JD 寻访功能。",
  "No. It generates a draft you can edit or revise. You decide what to share with your client.": "不会。它会生成可编辑的草稿，由你决定向客户分享什么。",
  "It is instructed to say when no candidate activity was verified and to show the missing facts before a recommendation.": "没有经核实的候选人活动时，它应如实说明，并在推荐前列出缺少的事实。",
  "Free": "免费版",
  "Try first role": "体验第一个职位",
  "1 AI sourcing preview": "1 次 AI 人才寻访体验",
  "1 client role preview": "1 个客户职位体验",
  "AI-sourced ranked candidate pool": "AI 寻访并排序的候选人池",
  "Top recommendations with outreach drafts": "重点人选推荐与联系草稿",
  "per month": "每月",
  "per month, billed annually": "每月，按年付款",
  "AI can split scans across sourcing angles": "AI 可按不同寻访方向分配扫描额度",
  "Useful profiles are deduped and ranked": "对有用的人才画像去重并排序",
  "LinkedIn outreach drafts for recommended candidates": "为推荐人选生成 LinkedIn 联系草稿",
  "CSV export and client-ready briefs": "CSV 导出与客户推荐材料",
  "AI can run more sourcing rounds per desk": "AI 可为每个职位进行更多轮寻访",
  "Start Pro": "开通 Pro 套餐",
  "Conversations": "对话",
  "Conversation": "当前对话",
  "Conversation history": "对话历史",
  "Open conversation history": "打开对话历史",
  "Close conversation history": "关闭对话历史",
  "Search conversations": "搜索对话",
  "Search titles and messages": "搜索标题和对话内容",
  "Search results": "搜索结果",
  "Searching conversations…": "正在搜索对话…",
  "Clear search": "清除搜索",
  "Drop a CSV or CV to import": "放开即可导入 CSV 或简历",
  "No matching conversations": "没有匹配的对话",
  "Conversation title": "对话标题",
  "Rename conversation": "重命名对话",
  "Save title": "保存标题",
  "Could not rename this conversation": "无法重命名对话",
  "Could not copy this message": "无法复制消息",
  "Copy message": "复制消息",
  "Close current work panel": "关闭当前工作面板",
  "What can I help you move forward?": "今天有什么工作要一起推进？",
  "Search the people I already know": "从已有候选人中查找",
  "Turn a JD into a clear brief": "把 JD 整理成清晰的职位要求",
  "Prepare a client-ready introduction": "准备给客户的人选介绍",
  "Find a candidate in my pool who ": "帮我从候选人池中找一位符合以下条件的人：",
  "I have a new client role. Here is the JD:\n\n": "我有一个新客户职位，JD 如下：\n\n",
  "Help me prepare a candidate submission for ": "帮我准备以下职位的候选人推荐：",
  "Sending…": "发送中…",
  "Hirelix is working": "Hirelix 正在处理",
  "Jump to latest": "跳到最新消息",
  "Your next message can be drafted while this reply finishes": "可以先写下一条消息，待回复完成后再发送",
  "Reporting timezone": "汇报时区",
  "Your AI credit allowance has ended. Your saved work is still available. Open Settings → Billing to subscribe or check your allowance.": "AI 工作额度已用完。已保存的工作仍可查看。请打开 设置 → 计费，订阅或查看额度。",
  "Your AI credit allowance has ended. Open Settings → Billing to continue.": "AI 工作额度已用完。请打开 设置 → 计费 后继续。",
  "Enter to send · Shift + Enter for a new line": "Enter 发送 · Shift + Enter 换行",
};
