import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {after,test} from "node:test";
import {sql} from "drizzle-orm";
import {db,closeDb} from "../../src/db/client";
import {createRole} from "../../src/lib/workspace/roles";
import {json,rows} from "../../src/lib/workspace/database";
import {saveFile} from "../../src/lib/workspace/files";
import {activeDocumentShare,publishDocument,readSharedDocument,revokeDocumentShare,sharedDocumentFile} from "../../src/lib/workspace/document-sharing";
import {updateDeliverable} from "../../src/lib/workspace/deliverables";
import type {Deliverable} from "../../src/lib/workspace/types";
const database=new URL(process.env.DATABASE_URL||"postgresql://invalid/invalid");
assert.ok(["localhost","127.0.0.1"].includes(database.hostname)&&database.pathname.startsWith("/hirelix_workspace_qa_"));
const owner=randomUUID();
after(async()=>{await db.execute(sql`UPDATE hirelix_private_jobs SET status='cancelled' WHERE user_id=${owner}::uuid AND status IN ('queued','running')`);await closeDb();});
test("real DB: share is owned, versioned, revocable and only exposes selected client content",async()=>{
 const role=await createRole(owner,{title:"QA Platform Lead",client_name:"QA Share Client",jd_text:"Platform operations"});
 const file=await saveFile(owner,{name:"selected.txt",type:"text/plain",bytes:Buffer.from("Fictional selected CV")});
 const hidden=await saveFile(owner,{name:"private.txt",type:"text/plain",bytes:Buffer.from("Private unselected file")});
 const source={audience:"client",language:"zh",role:{title:role.title,client_name:role.client_name,client_contact:{email:"hidden@example.test"}},people:[{id:randomUUID(),name:"QA Person",headline:"Platform lead",location:"London",email:"private@example.test",notes:"PRIVATE NOTE"}],records:[{content:"PRIVATE SOURCE"}],files:[{id:file.id,person_id:randomUUID(),name:file.name,sha256:file.sha256}]};
 const [doc]=await rows<Deliverable>(sql`INSERT INTO hirelix_private_deliverables(user_id,role_id,kind,title,content,source_snapshot) VALUES(${owner}::uuid,${role.id}::uuid,'submission','QA subject','Reviewed client content',${json(source)}) RETURNING *`);
 await assert.rejects(()=>publishDocument(randomUUID(),doc.id,doc.version),/not found/);
 await assert.rejects(()=>publishDocument(owner,doc.id,doc.version+1),/changed|version/i);
 const share=await publishDocument(owner,doc.id,doc.version);
 const token=share.path.split('/').at(-1)!;
 assert.equal((await publishDocument(owner,doc.id,doc.version)).id,share.id);
 assert.equal((await activeDocumentShare(owner,doc.id))?.path,share.path);
 const publicCopy=await readSharedDocument(token);
 assert(publicCopy);
 const serialized=JSON.stringify(publicCopy.snapshot);
 assert.doesNotMatch(serialized,/PRIVATE|private@example|hidden@example/);
 assert.equal((await sharedDocumentFile(token,file.id)).bytes.toString(),"Fictional selected CV");
 await assert.rejects(()=>sharedDocumentFile(token,hidden.id),/unavailable/);
 assert.equal(await readSharedDocument(token.slice(0,-1)+(token.endsWith('a')?'b':'a')),null);
 const updated=await updateDeliverable(owner,doc.id,{title:"Revised subject",content:"Revised client content",expected_version:doc.version});
 assert.equal((await readSharedDocument(token))?.snapshot.title,"QA subject");
 const next=await publishDocument(owner,doc.id,updated.version);
 assert.equal(await readSharedDocument(token),null);
 const nextToken=next.path.split('/').at(-1)!;
 assert.equal((await readSharedDocument(nextToken))?.snapshot.title,"Revised subject");
 await revokeDocumentShare(owner,doc.id);
 assert.equal(await readSharedDocument(nextToken),null);
 await assert.rejects(()=>sharedDocumentFile(nextToken,file.id),/unavailable/);
 const expires=await publishDocument(owner,doc.id,updated.version);
 await db.execute(sql`UPDATE hirelix_private_document_shares SET expires_at=now()-interval '1 second' WHERE id=${expires.id}::uuid`);
 assert.equal(await readSharedDocument(expires.path.split('/').at(-1)!),null);
 await db.execute(sql`UPDATE hirelix_private_deliverables SET source_snapshot=source_snapshot || '{"audience":"internal"}'::jsonb WHERE id=${doc.id}::uuid`);
 await assert.rejects(()=>publishDocument(owner,doc.id,updated.version),/Only client/);
});
