import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {after,test} from "node:test";
import {sql} from "drizzle-orm";
import {db,closeDb} from "../../src/db/client";
import {rows} from "../../src/lib/workspace/database";
import {createRole,updateRelationship} from "../../src/lib/workspace/roles";
import {createPerson} from "../../src/lib/workspace/people";
const database=new URL(process.env.DATABASE_URL||"postgres://invalid/invalid");
assert.ok(["localhost","127.0.0.1"].includes(database.hostname)&&database.pathname.startsWith("/hirelix_workspace_qa_"));
const owner=randomUUID();
after(async()=>{await db.execute(sql`UPDATE hirelix_private_jobs SET status='cancelled' WHERE user_id=${owner}::uuid AND status IN ('queued','running')`);await closeDb();});
test("real PG: current refusal blocks both email paths and public links, including an old shared snapshot",async()=>{
 const {publishDocument,readSharedDocument,activeDocumentShare,clientDocument,assertSharingAllowed}=await import('../../src/lib/workspace/document-sharing');
 const {reserveEmailDelivery,reserveConversationEmail}=await import('../../src/lib/workspace/gmail');
 const {linkPerson}=await import('../../src/lib/workspace/roles');
 const {addRecord}=await import('../../src/lib/workspace/records');
 const {json}=await import('../../src/lib/workspace/database');
 const role=await createRole(owner,{title:'Analytics Lead',client_name:'QA Deltafield',jd_text:'Lead analytics'});
 const person=await createPerson(owner,{name:'QA Taylor Brook'});
 const relation=await linkPerson(owner,role.id,person.id);
 const source={audience:'client',language:'en',people:[{id:person.id,name:person.name}],files:[]};
 const [doc]=await rows<import('../../src/lib/workspace/types').Deliverable>(sql`INSERT INTO hirelix_private_deliverables(user_id,role_id,kind,title,content,source_snapshot) VALUES(${owner}::uuid,${role.id}::uuid,'submission','QA share boundary','Factual client text.',${json(source)}) RETURNING *`);
 const shared=await publishDocument(owner,doc.id,doc.version);const token=shared.path.split('/').at(-1)!;assert(await readSharedDocument(token));
 const evidence=await addRecord(owner,{role_id:role.id,person_id:person.id,kind:'note',title:'Sharing decision',content:'Candidate explicitly declined sharing with this client role.'});
 await updateRelationship(owner,role.id,person.id,{...relation,permission:'declined',permission_record_id:evidence.id,expected_version:relation.version});
 await assert.rejects(()=>assertSharingAllowed(owner,role.id,clientDocument(doc)),/declined sharing/);
 await assert.rejects(()=>publishDocument(owner,doc.id,doc.version),/declined sharing/);
 assert.equal(await readSharedDocument(token),null);
 await assert.rejects(()=>activeDocumentShare(owner,doc.id),/declined sharing/);
 await assert.rejects(()=>reserveEmailDelivery(owner,doc.id,{to:'client@example.test',expected_version:doc.version,request_key:randomUUID()},'sender@example.test','<qa@test>'),/declined sharing/);
 await assert.rejects(()=>reserveConversationEmail(owner,{from:'sender@example.test',to:'client@example.test',title:doc.title,content:doc.content,files:[],document_id:doc.id,document_version:doc.version},randomUUID(),'<qa@test>',async()=>{}),/declined sharing/);
 assert.equal((await rows(sql`SELECT id FROM hirelix_private_email_deliveries WHERE user_id=${owner}::uuid`)).length,0);
});
